### PR TITLE
[argo-cd] Added simple PrometheusRule

### PR DESCRIPTION
**Pull request by mnaser**
This patch adds a few simple rules which you can leverage to make
sure that your infrastructure is up to date.  They are optional
and opt-in only.

There is not a lot of customization initially but this is a start
of a simple framework to deliver this.

Checklist:

* [X] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [X] I have signed the CLA and the build is green.
* [X] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mnaser** [comment]
Hi there,

I was hoping that we can iterate onto this a step down the line if that’s cool :)

If we can land this then I totally can do the extra work to slowly make it more and more configurable. 

Thanks,
Mohammed

**Comment by seanson** [comment]
I would prefer to have an update with a standard configurable change than intermediate versions later. It should be a fairly trivial change:

- Move spec.groups list to values.yaml
- Replacing the spec.groups list with `{{- toYaml .Values.controller.metrics.rules | nindent <x> }}`

**Comment by mnaser** [comment]
voila :)

**Comment by seanson** [comment]
Awesome, thanks for the change @mnaser! One last request, the sample rules in `values.yaml` should be commented out and the default `spec` value should be `[]` as Prometheus alerts are likely to vary wildly by environment in requirements. These rules are awesome but should be up to the user to add if they'd like.
Should be good to merge after that!

**Comment by mnaser** [comment]
donezo :+1:

**Comment by seanson** [comment]
Looks good, merged an upstream selector fix. Thanks for the work @mnaser!

**Comment by mnaser** [comment]
yay, thanks!

**Pull request merged**
