### PR TITLE
fix(argo-cd): Align imagePullSecrets for redis-secret-init Job

### PR DESCRIPTION
**Pull request by DoumLaberge**
Correction of the imagepullsecret for redis

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Review by yu-croco — CHANGES_REQUESTED** [review]
Thank you for your PR.
Please fulfill the items in your PR description.
>I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
 I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
 I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
 Any new values are backwards compatible and/or have sensible default.
 I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
 My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

**Comment by DoumLaberge** [comment]
Can someone just include the code in the main branch please.  I don't have time to jump in all this hoop.  Sorry

**Comment by mmarisetty** [comment]
I hope this one fix this problem ?
Which i'm facing this error:
job argocd-redis-secret-init failed: BackoffLimitExceeded

https://github.com/argoproj/argo-cd/issues/18356

**Comment by mmarisetty** [comment]
> I hope this one fix this problem ? Which i'm facing this error: job argocd-redis-secret-init failed: BackoffLimitExceeded
> 
> [argoproj/argo-cd#18356](https://github.com/argoproj/argo-cd/issues/18356)

Please merge the PR. Thank you !

**Comment by mmarisetty** [comment]
> > I hope this one fix this problem ? Which i'm facing this error: job argocd-redis-secret-init failed: BackoffLimitExceeded
> > [argoproj/argo-cd#18356](https://github.com/argoproj/argo-cd/issues/18356)
> 
> Please merge the PR. Thank you !

redisSecretInit:
enabled: false

with this it will work.

**Review by mkilchhofer — APPROVED** [review]

**Review by mbevc1 — APPROVED** [review]

**Pull request merged**
