### PR TITLE
docs: Rename argocd references to argoworkflows in workflow chart

### PR DESCRIPTION
**Pull request by nielstenboom**
Small documentation change of the values.yaml of the argo workflows chart.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by vladlosev — COMMENTED** [review]
This will need a chart version bump, to satisfy the CI checks.

**Review by vladlosev — COMMENTED** [review]
I'll have to ask you to bump the version again. :-/
And please also update the change description in the `artifacthub.io/changes` annotation in `Chart.yaml`.

**Comment by nielstenboom** [comment]
Haha that's alright, done!

**Review by vladlosev — APPROVED** [review]
LGTM

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
