### PR TITLE
feat(argo-cd): Upgrade redis to 7.0.0

### PR DESCRIPTION
**Pull request by sathieu**
Including CVEs.

Ref: https://github.com/redis/redis/blob/7.0/00-RELEASENOTES

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by sathieu** [comment]
See also https://github.com/DandyDeveloper/charts/issues/191

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Thanks for your contribution. Unfortunately we do not implement things here that differs from the upstream manifests over there: https://github.com/argoproj/argo-cd/blob/v2.3.3/manifests/base/redis/argocd-redis-deployment.yaml#L24

Please read the README:

> ### Synchronizing Changes from Original Repository
> 
> In the original [Argo CD repository](https://github.com/argoproj/argo-cd/) an [`manifests/install.yaml`](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml) is generated using `kustomize`. It's the basis for the installation as [described in the docs](https://argo-cd.readthedocs.io/en/stable/getting_started/#1-install-argo-cd).
> 
> When installing Argo CD using this helm chart the user should have a similar experience and configuration rolled out. Hence, it makes sense to try to achieve a similar output of rendered `.yaml` resources when calling `helm template` using the default settings in `values.yaml`.

Can you please file a PR/ an issue [upstream](https://github.com/argoproj/argo-cd/issues)?

**Comment by sathieu** [comment]
> Can you please file a PR/ an issue [upstream](https://github.com/argoproj/argo-cd/issues)?

Done https://github.com/argoproj/argo-cd/pull/9250.

**Comment by sathieu** [comment]
@mkilchhofer https://github.com/argoproj/argo-cd/pull/9250 was merged, and I've rebased this PR. Please review again :pray:.

**Comment by mbevc1** [comment]
Thanks! I reckon we'll need to wait until upstream cuts a new release, i.e. v2.3.4 and align that with bumping the release in the Chart.

**Comment by mkilchhofer** [comment]
Merged your work into PR https://github.com/argoproj/argo-helm/pull/1325, will close this as mentioned PR is merged

**Pull request closed without merging**
