### PR TITLE
fix(argo-cd): Remove unneeded static-files volume

### PR DESCRIPTION
**Pull request by Sea-you**
Remove the unnecessary `static-files` volume to fix Velero backups https://github.com/argoproj/argo-cd/issues/8714

Signed-off-by: Domonkos Cinke <seayou@gmail.com>

---
Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
This volume is present in the upstream manifests:
https://github.com/argoproj/argo-cd/blob/v2.3.3/manifests/base/server/argocd-server-deployment.yaml#L213-L214

We cannot remove it here unless upstream also removes them as we follow the policy mentioned in the README.md

> Synchronizing Changes from Original Repository
> 
> In the original [Argo CD repository](https://github.com/argoproj/argo-cd/) an [manifests/install.yaml](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml) is generated using kustomize. It's the basis for the installation as [described in the docs](https://argo-cd.readthedocs.io/en/stable/getting_started/#1-install-argo-cd).
> 
> **When installing Argo CD using this helm chart the user should have a similar experience and configuration rolled out.** Hence, it makes sense to try to achieve a similar output of rendered .yaml resources when calling helm template using the default settings in values.yaml.

**Comment by Sea-you** [comment]
Thanks, I raised a PR there too, to fix this https://github.com/argoproj/argo-cd/pull/9013

**Comment by Sea-you** [comment]
@mkilchhofer PTAL, upstream merged the related PR. 

Do you also want me to bump the chart version or do you usually prefer to accumulate more changes and then bump?

**Comment by mkilchhofer** [comment]
> @mkilchhofer PTAL, upstream merged the related PR.
> 
> Do you also want me to bump the chart version or do you usually prefer to accumulate more changes and then bump?

Nice, thanks for promoting this upstream. I already bumped the chart version for you :-)

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
