### PR TITLE
fix(argo-workflows): fixes server sa annotations and ingress

### LINKED ISSUE #745: argo-workflows - YAML parser error if server.serviceAccount.annotations are provided
**Describe the bug**
YAML parser error if server.serviceAccount.annotations are provided.

Exact error
```
Error: YAML parse error on argo/charts/argo-workflows/templates/server/server-sa.yaml: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context
```
This gives error
```
server:
  serviceAccount:
	create: true
	name: argo-workflows-server
	annotations:
	  a: b
```
This works

```
server:
  serviceAccount:
	create: true
	name: argo-workflows-server
	annotations: { }
```
**To Reproduce**
1. Add annotation to server service account

**Expected behavior**
annotations should be added.

**Screenshots**
None

**Additional context**
None

### LINKED ISSUE #746: argo-workflows - Unable to create ingress on Kubernetes v1.19
**Describe the bug**
Unable to create ingress on Kubernetes v1.19

Error details below
```
error validating data: 
[
ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, 
ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend
]
```

**To Reproduce**
1. on cluster running K8s v1.19 or above create an ingress

**Expected behavior**
ingress should be created.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by abhinavkhanna-sf**
Fixes #745 
Fixes #746 

@oliverbaehler Can you please review

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [X] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by oliverbaehler — APPROVED** [review]
lgtm

**Comment by oliverbaehler** [comment]
#741 Will resolve the linting issues, give is another 10 minutes

**Review by oliverbaehler — CHANGES_REQUESTED** [review]
Requires Bugfix Version Bump

**Review by mkilchhofer — APPROVED** [review]
LGTM

**Review by oliverbaehler — APPROVED** [review]
lgtm

**Comment by oliverbaehler** [comment]
ohh :dagger:

**Pull request merged**
