### PR TITLE
fix(argo-workflows): fix clusterworkflowtemplates disabled flag

### PR DESCRIPTION
**Pull request by PidgeyBE**
Fix for https://github.com/argoproj/argo-helm/issues/1925

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by jmeridth** [comment]
Need to update Chart.yaml version and artifacthub annotations at bottom please.

**Comment by PidgeyBE** [comment]
@jmeridth I've updated artifacthub annotations and Chart version. But it's hard to keep up with the version changes :grimacing:

**Comment by PidgeyBE** [comment]
@jmeridth I've updated artifacthub annotations and Chart version. But it's hard to keep up with the version changes :grimacing:

**Review by jmeridth — APPROVED** [review]

**Review by yu-croco — APPROVED** [review]
LGTM

**Pull request merged**
