### PR TITLE
feat(argocd-image-updater): Add missing config map key for git commit-message-template

### LINKED ISSUE #1004: missing mount  commit.template for argocd-image-updater
### Describe the bug

when installed it, we will configure the commit.template in the configmap, but here in the deployment.yaml. it doesn't mount it here, now only registries.conf mounted
```
...
      volumes:
      - configMap:
          items:
          - key: registries.conf
            path: registries.conf
          name: argocd-image-updater-config
        name: registries-conf
...
```

### Related helm chart

argocd-image-updater

### To Reproduce

any deployment will have same result

### Expected behavior

```
      volumes:
      - configMap:
          items:
          - key: registries.conf
            path: registries.conf
          - key: commit.template
            path: commit.template
          name: argocd-image-updater-config

```

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nickjn92**
Changes:

After deploying argocd-image-updater through the helm chart and following the documentation here https://argocd-image-updater.readthedocs.io/en/stable/configuration/applications/#changing-the-git-commit-message, one should edit the git.commit-message-template in the argocd-image-updater-config configmap to get a custom commit message. Even after restarting the pod no change to the commit message can be seen, it still uses the default message.

I posted the bug report on https://github.com/argoproj-labs/argocd-image-updater/issues/277 where @jannfis caught the issue 
> The image updater manifests have a volume mount for the commit message [here](https://github.com/argoproj-labs/argocd-image-updater/blob/e42f982935566e7f1dd3f322c732727e681ff23a/manifests/base/deployment/argocd-image-updater-deployment.yaml#L111), but this seems to be missing in the Helm chart's version of the deployment resource [here](https://github.com/argoproj/argo-helm/blob/c87255c165ec101123d9e7b7b041efb09fe19322/charts/argocd-image-updater/templates/deployment.yaml#L82)

Resolves #1004

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — COMMENTED** [review]
Your change was not enough to achieve what you need so I diffed the upstream manifests and updated the manifests here also. Are you able to test these changes?

**Comment by nickjn92** [comment]
> Your change was not enough to achieve what you need so I diffed the upstream manifests and updated the manifests here also. Are you able to test these changes?

Yes ill deploy the helm chart from the fork and verify that the changes work :) Thanks for the help!

**Comment by mkilchhofer** [comment]
> > Your change was not enough to achieve what you need so I diffed the upstream manifests and updated the manifests here also. Are you able to test these changes?
> 
> Yes ill deploy the helm chart from the fork and verify that the changes work :) Thanks for the help!

Any updates on your tests? :-)

**Comment by nickjn92** [comment]
> > > Your change was not enough to achieve what you need so I diffed the upstream manifests and updated the manifests here also. Are you able to test these changes?
> > 
> > 
> > Yes ill deploy the helm chart from the fork and verify that the changes work :) Thanks for the help!
> 
> Any updates on your tests? :-)

Sorry, got caught up in a lot of stuff with work. Ive replaced our current argocd-image-updater deployment with the forked one this morning and  setup custom template, user and email. Ill verify the behaviour and will get back to you within the hour

**Comment by nickjn92** [comment]
> > > Your change was not enough to achieve what you need so I diffed the upstream manifests and updated the manifests here also. Are you able to test these changes?
> > 
> > 
> > Yes ill deploy the helm chart from the fork and verify that the changes work :) Thanks for the help!
> 
> Any updates on your tests? :-)

```
Author: CustomUser <custom@org.com>
Date:   Mon Nov 22 07:13:09 2021 +0000

    [skip ci] custom message, build: automatic update of pos-connector
    
    updates image pej-dev/docker/status-screen/pos-connector tag 'main-1637330577-15b5bd3d75ab5449b91aba0f0f0b3f6061327614' to 'main-1637565152-testlatest'

commit 386ed6f488ab97076351283c7e3308c8666e448d

``` 
It works as expected  now :+1: :fireworks:

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
