### PR TITLE
feat(argo-rollouts): upgrade to v1.2.0

### LINKED ISSUE #1112: Argo-Rollouts: Unknown flag: --leader-elect
### Describe the bug

when setting `controller.replicas` to a value > 1, controller replicas will not start and return the error `Error: unknown flag: --leader-elect`.

Helm Chart version: `2.9.3`

```
❯ k get po/argo-rollouts-d5cd7fd8-rhdh5 -o json | jq -r '.spec.containers[0].image'
quay.io/argoproj/argo-rollouts:v1.1.1
```

### Related helm chart

argo-rollouts

### To Reproduce

1.  Deploy chart version 2.9.3 with the value `controller.replicas` set to 2.
2.  Observe the controller pods enter CrashLoopBackoff

### Expected behavior

controller pods work correctly

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang <hui.kang@salesforce.com>

fix #1112 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by huikang** [comment]
@mkilchhofer , could you help understand why linting the doc failed? I tried several changes, but all failed. Thanks.

**Comment by mkilchhofer** [comment]
> @mkilchhofer , could you help understand why linting the doc failed? I tried several changes, but all failed. Thanks.

Yes, it seems that you didnt update the README.md file by executing helm-docs. Instead you updated the file manually. There are 3 more changes open ;)

**Comment by huikang** [comment]
> > @mkilchhofer , could you help understand why linting the doc failed? I tried several changes, but all failed. Thanks.
> 
> Yes, it seems that you didnt update the README.md file by executing helm-docs. Instead you updated the file manually. There are 3 more changes open ;)

Thanks for the hint. Tests are passed after I run `helm-doc.sh`. Please help review the PR when you have a chance.

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Hmm this would be new here to publish a chart for a project prerelease. Shall we proceed with that or wait until rollouts have a final 1.2 release?

Open things:
- Bump minor chart version
- Update Line 14 in Chart.yaml
- maybe add a new annotation in Chart.yaml 
  ```
  annotations:
    artifacthub.io/prerelease: "true"
  ```

**Comment by huikang** [comment]
> Hmm this would be new here to publish a chart for a project prerelease. Shall we proceed with that or wait until rollouts have a final 1.2 release?
> 
> Open things:
> 
>     * Bump minor chart version
> 
>     * Update Line 14 in Chart.yaml
> 
>     * maybe add a new annotation in Chart.yaml
>       ```
>       annotations:
>         artifacthub.io/prerelease: "true"
>       ```

The current release of argo-helm doesn't work due to #1112 , so we probably need this version for the pre-release version of argo-rollouts.
I'm not sure where to put the annotation; please take a look at the new commit. Thanks.

**Comment by hairmare** [comment]
I've been using rc1 and subsequently rc2 with this chart for a while now because K8s 1.22 (or even 1.21, i'm not sure 🤔) support is in 1.2 (as per https://github.com/argoproj/argo-rollouts/discussions/1688)

I'm not in production with my deployment (yet) and don't have any background on what is holding up 1.2 tho

**Comment by mkilchhofer** [comment]
The final 1.2 release is here: https://github.com/argoproj/argo-rollouts/releases/tag/v1.2.0
🎉

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
L14 in Chart.yaml needs to be adapted for the current change

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
