### PR TITLE
docs(argo-cd): minor clarification around CRDs for Argo-CD

### PR DESCRIPTION
**Pull request by object88**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by object88** [comment]
This is in reference to [this discussion re: CRDs](https://github.com/argoproj/argo-helm/discussions/1476)

**Comment by pdrastil** [comment]
Hi @object88 thanks for the PR. Can you please fix the whitespace in gotpl so the build will pass?

**Comment by pdrastil** [comment]
The Chart.yaml should contain what has changed in `artifacthub.io/changes` section

**Comment by object88** [comment]
Whoops.

**Comment by object88** [comment]
Hah, this is not _quite_ going as planned.  Still trying.  :D

**Review by pdrastil — APPROVED** [review]

**Review by mkilchhofer — COMMENTED** [review]
👍

**Pull request merged**
