### PR TITLE
chore(argo-cd): Update dependency argoproj/argo-cd to v2.12.7

### PR DESCRIPTION
**Pull request by YaronL16**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by tico24** [comment]
12.13 is out and we don't backport to older versions I'm afraid.

**Comment by mbevc1** [comment]
I think title is wrong, and we should probably bump this to latest: https://github.com/argoproj/argo-cd/releases/tag/v2.13.1

**Comment by YaronL16** [comment]
> 12.13 is out and we don't backport to older versions I'm afraid.

Yes but a new v2.12.x release dropped, why not make include it in a chart?
After all like is mentioned in the documentation:
> Helm charts are intended to be created for all non-patched releases of Argo CD, Workflows, Rollouts, and Events.

**Comment by jmeridth** [comment]
@YaronL16 once a new minor version is released, we don't create patches for previous versions.  This has been a policy since I've been involved in this project.  The maintenance involved exceeds our availability for that effort currently.

The workaround we've suggested in the past is for a user to point their chosen [image tag](https://github.com/argoproj/argo-helm/blob/168bc63bd6b65586720ebbcea197dbce123c03f5/charts/argo-cd/values.yaml#L62) in their values.yaml to the patched image.  The only gotcha is if there are CRD changes in that patch version (usually rare).

I'm going to close this as it does not match our current policy.  Thank you for your understanding and hope the workaround can work for you.

**Comment by YaronL16** [comment]
@jmeridth 

Okay got it, honestly don't really see why not to allow simple changes like this but I'll probably make the updated chart just for my team
Thanks

**Comment by jmeridth** [comment]
> @jmeridth 
> 
> Okay got it, honestly don't really see why not to allow simple changes like this but I'll probably make the updated chart just for my team
> Thanks

@YaronL16 are you volunteering to help us maintain patch level version updates from the upstream projects? All of them? We agree. It's easy for one. Or maybe a couple. But maintaining all of them requires more effort than we currently have to support it.

We do truly appreciate that you took time and created a pull request. We do not close it easily. We understand this PR could be a gateway to many more PRs. Is that what this is?

If you feel very strongly about this and are volunteering to take on the responsibility, especially since you believe it to be "simple changes", we can discuss it. If so, please start a thread in the CNCF slack in the #argo-helm-charts public channel and reference this PR. 

Otherwise, thank you for your understanding and accepting of the current workarounds.

**Pull request closed without merging**
