### PR TITLE
feat: Enable HA deployment for Dex component

### PR DESCRIPTION
**Pull request by pdrastil**
This PR allows to scale Dex deployment for high availability. It also adds missing liveness / readiness probes so K8s can restart container in case Dex server is not responding for some reason. Implementation is inspired by [Dex chart](https://github.com/dexidp/helm-charts/tree/master/charts/dex)

## Open questions

When looking into deployment I was wondering on following implementation. If you can please respond to following.

1) Why are the container ports configurable via values.yaml? Only reason I can see is in case user would provide custom image, however init container that uses [argocd-dex](https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/util/dex/config.go#L12) will always generate configuration with hardcoded port numbers. Maybe fixed port numbers should be used in deployment instead so user cannot make deployment non-functioning.

2) Why is port for metrics / telemetry hidden in deployment via `metrics.enable`? This endpoint is always running in container so I would expect that the port is also present in Deployment / Service. Maybe following approach to auto-detect Prometheus on ServiceMonitor can be used as another improvement?

```yaml
{{- if and metrics.enabled .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
```

### CODE REVIEW

**Comment by pdrastil** [comment]
Another question to upstream maintainers. Why did you actually decided to use / maintain your custom Dex deployment compared to dependency sub-chart from dexidp.io? Just because of argocd-dex util?

**Comment by mkilchhofer** [comment]
Hi 👋 , thanks for your contribution.

HA for Dex is not supported:

> The argocd-dex-server uses an in-memory database, and two or more instances would have inconsistent data. argocd-redis is pre-configured with the understanding of only three total redis servers/sentinels.
(Ref: https://argoproj.github.io/argo-cd/operator-manual/high_availability/#argocd-dex-server-argocd-redis)

This repo here is community maintained, we only implement things which is supported by the upstream project(s). Please have a look in the upstream repo for HA manifests and file a bug/feature request over there: https://github.com/argoproj/argo-cd/tree/master/manifests/ha

**Comment by pdrastil** [comment]
@mkilchhofer Thanks for the information. Can I open new PR that adds just a probes? We found out that Dex container fails at least once a month and is not properly restarted which was the main motivation behind this PR.

**Comment by mkilchhofer** [comment]
Does our dex version support health endpoints already? I think they were missing for quite a long time

**Comment by pdrastil** [comment]
Yes dex itself supports this via telemetry (metrics) port on `/healthz/live` and `/healthz/ready` endpoints. It was included in this PR.

**Comment by mkilchhofer** [comment]
Ah yup, I doublechecked it: Dex implemented these endpoints in version 2.28.0 and we use 2.28.1, but the official/upstream manifests for ArgoCD 2.0.5 uses dex-2.27.0:
https://github.com/argoproj/argo-cd/blob/v2.0.5/manifests/base/dex/argocd-dex-server-deployment.yaml

Yeah, feel free to implement it and file a PR. I think implement it as optional for now would be great.

**Comment by pdrastil** [comment]
@mkilchhofer - Thank - new PR for probes is here https://github.com/argoproj/argo-helm/pull/880

**Pull request closed without merging**
