### PR TITLE
fix(argo-cd): Fix duplicate secret

### LINKED ISSUE #756: Certificate secret name conflicts with argocd secret name
If you create certificate using Cert-Manager from this chart, the secret is named `argocd-secret` 

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/certificate.yaml#L26

Which is of type `kubernetes.io/tls`

The argocd secret containing argocd secrets is also named `argocd-secret`  

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-configs/argocd-secret.yaml#L5

Which is of type `Opaque`. 

This should not work.

### PR DESCRIPTION
**Pull request by AtzeDeVries**
Fixes #756
The TLS secret created by cert-manager has the same secret name as the argocd secret. This should not work. This PR will fix it. 

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Needs rebase

**Comment by AtzeDeVries** [comment]
I looks like that is 'Allow edits and access by maintainers' feature is only enabled if forked by a user, not a Org. I've forked is a an org. Check https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/4

Anyway we can work around this issue? If not i think i have to recreate this PR with my own account.

**Comment by mkilchhofer** [comment]
> I looks like that is 'Allow edits and access by maintainers' feature is only enabled if forked by a user, not a Org. I've forked is a an org. Check https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/4
> 
> Anyway we can work around this issue? If not i think i have to recreate this PR with my own account.

Good to know, I did not know that.
Checks are green now :-) your `Merge branch 'master' into fix-duplicate-sercret` fixed it. I can now merge.

Thank you very much for this contribution.

**Review by mkilchhofer — APPROVED** [review]
LGTM

**Pull request merged**
