### PR TITLE
fix(argo-cd): Update github SSH key fingerprint

### PR DESCRIPTION
**Pull request by hamza3202**
Fixes: argoproj/argo-helm/issues/1019
Github has two new fingerprints. This PR adds those fingerprints to default values.

Ref: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

Signed-off-by: Muhammad Hamza Zaib <hamzazaib3202@gmail.com>

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by hamza3202** [comment]
@mbevc1 could you please review this PR? Argo CD is not able to communicate with github right now.

**Comment by mbevc1** [comment]
@hamza3202 thanks for the contribution. Seems old keys have been dropped. Could we remove those and replace third one as well?
https://api.github.com/meta

**Comment by hamza3202** [comment]
@mbevc1 The three signatures added right now are the correct ones. You can generate and compare the fingerprints with the ones provided at https://api.github.com/meta by doing the following

```
> echo "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" | tee key | ssh-keygen -lf -
256 SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM no comment (ECDSA)

> echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" | tee key | ssh-keygen -lf -
256 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU no comment (ED25519)

> echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" | tee key | ssh-keygen -lf -
2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 no comment (RSA)

**Comment by idrissneumann** [comment]
For information: I did pretty the same fix here: https://github.com/argoproj/argo-helm/pull/1020 (which I just closed because this pr is a little bit older ^^ ).

And I opened an issue here that you can link to this pr: https://github.com/argoproj/argo-helm/issues/1019

**Review by idrissneumann — APPROVED** [review]

**Review by mkilchhofer — APPROVED** [review]
lgtm. Thanks for your contribution

**Comment by mbevc1** [comment]
Thanks, looks good now :+1:

**Comment by mbevc1** [comment]
It can be a separate PR, but we probable want to clean up old keys as they are not in use any more. Cheers for adding new ones in :+1:

**Comment by hamza3202** [comment]
> It can be a separate PR, but we probable want to clean up old keys as they are not in use any more. Cheers for adding new ones in +1

@mbevc1 which key are you referring to as the `old keys`?

**Comment by mbevc1** [comment]
I reckon those are not used anymore:
https://github.com/argoproj/argo-helm/pull/1018/files#diff-9eb59d56febda5e405748483497dfdc0c2dfbe9b4f386a12f0180c98d99051e0R1490-R1491

**Comment by hamza3202** [comment]
Those are for gitlab not github.

**Comment by mbevc1** [comment]
Ah, your are right. Sorry about that, GH diff got me confused for a bit here :) All good. Thanks again :+1:

**Pull request merged**
