### PR TITLE
configurable casbin file

### PR DESCRIPTION
**Pull request by ragarcia26**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed the CLA and the build is green.
* [ ] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by ragarcia26** [comment]
I believe this needs the updated argo-cd image to be used with the updated casbin configuration. That has not been completed/merged

**Comment by spencergilbert** [comment]
Looks like we should leave this in WIP until argocd has implemented custom casbin support?

**Comment by seanson** [comment]
I don't currently see any documentation about casbin support, are we still waiting for upstream support here?

**Comment by alexec** [comment]
Stale.

**Pull request closed without merging**
