### PR TITLE
feat(argo-cd): represent cluster credentials as a map

### LINKED ISSUE #2592: Change clusterCredentials type to map
### Is your feature request related to a problem?

Helm [does not support merging arrays](https://github.com/helm/helm/issues/3486) so it's not possible to have for instance cluster declarations in separate "values" files (in view of encrypting them with different keys).

```yaml
configs:
  clusterCredentials:
    - name: my-cluster
      server: https://example.com:6443
      config:
        bearerToken: "foo"
        tlsClientConfig:
          insecure: false
          caData: "bar"
```

### Related helm chart

argo-cd

### Describe the solution you'd like

Declare clusters with the same syntax as `configs.repositories`:

```yaml
configs:
  clusterCredentials:
    my-cluster:
      server: https://example.com:6443
      config:
        bearerToken: "foo"
        tlsClientConfig:
          insecure: false
          caData: "bar"
```

as each cluster is represented by a key in the map `configs.clusterCredentials` it'd be possible for Helm to merge multiple clusters declared in separate values files.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nbarrientos**
Closes #2592.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

~I'll re-generate the docs~ and bump the version if this change request goes forward. This contains non-backwards compatible changes. The rationale for this change is in the issue it closes.

Thanks for considering it.

### CODE REVIEW

**Comment by jgranieczny** [comment]
Hi, any news on this? I would be very useful for us.

**Comment by pdrastil** [comment]
Hi, I'm for getting this in main. As this is breaking change for lots of people I would personally bundle this with another breaking things in next major release or do it as 2 phase process where old / new implementation lives side by side and old one will be removed later.

**Comment by nbarrientos** [comment]
Thanks! Fine for me to bundle with more breaking changes in the future; we're okay with keeping a local fork in the meantime.

**Comment by mkilchhofer** [comment]
> Hi, I'm for getting this in main. As this is breaking change for lots of people I would personally bundle this with another breaking things in next major release or do it as 2 phase process where old / new implementation lives side by side and old one will be removed later.

We can also create multiple breaking change, IMHO we do not need to wait. But I am fine with both :)

**Comment by nbarrientos** [comment]
Wondering if we could give this a push this week? :)

**Comment by mbevc1** [comment]
There are some conflicts that needs resolving as well

**Comment by nbarrientos** [comment]
Yes, no worries, I'll fix that once somebody gives me the green light. I'd rather to avoid having to fix them several times.

**Comment by mkilchhofer** [comment]
🟢 from my side 👍

**Comment by mbevc1** [comment]
Same :heavy_check_mark:

**Review by yu-croco — APPROVED** [review]

**Review by mbevc1 — APPROVED** [review]

**Comment by nbarrientos** [comment]
Conflicts resolved, version bumped to 7.0.0 due to the backwards-incompatible change.

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Line 10 and 14 also requires changes

- `{{- with .labels }}`
- `{{- with .annotations }}`

**Comment by nbarrientos** [comment]
> Line 10 and 14 also requires changes
> 
>     * `{{- with .labels }}`
> 
>     * `{{- with .annotations }}`

Thanks for the review.

I've added the requested changes, whoever it works (Helm v3.14.3) without specifying the scope in the `with` block. Perhaps inside the `range`, within the `with` block the context expands to all the local variables (in that case `$cluster_key` and `$cluster_value`).

With these values:

```yaml
configs:
  clusterCredentials:
    mycluster2:
      server: https://mycluster2.example.com
      labels:
        foo: bar
      annotations:
        bar: foo
      namespaces: namespace1,namespace2
      clusterResources: true
      config:
        bearerToken: "<authentication token>"
        tlsClientConfig:
          insecure: false
          caData: "<base64 encoded certificate>"
```

The Secret object renders fine with and without the modifications.

**Review by mkilchhofer — APPROVED** [review]
Thanks a lot @nbarrientos 🙏

**Review by mbevc1 — APPROVED** [review]

**Pull request merged**
