### PR TITLE
feat(argo-cd): change application-controller to StatefulSet

### PR DESCRIPTION
**Pull request by mr-sour**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mr-sour** [comment]
Finishes https://github.com/argoproj/argo-helm/issues/492

**Comment by yydzhou** [comment]
Any reason this PR is not approved/merged?

**Comment by spencergilbert** [comment]
@seanson I'm wondering if this should have a more notable version bump given the change, do you have any thoughts? It looks like based on @mr-sour's testing there _shouldn't_ be any impact but it might not be nice if someone was caught unaware.

**Comment by seanson** [comment]
> @seanson I'm wondering if this should have a more notable version bump given the change, do you have any thoughts? It looks like based on @mr-sour's testing there _shouldn't_ be any impact but it might not be nice if someone was caught unaware.

Ahh definitely, a resource type change is definitely worthy of a minor version bump.

**Review by seanson — APPROVED** [review]

**Comment by Junnplus** [comment]
@seanson any progress on this? I make a pr https://github.com/argoproj/argo-helm/pull/520 for upgrade to v1.8.1, also need change deployment to statefulset of application-controller.

**Comment by seanson** [comment]
I'm going to push this behind a feature flag so we can give people the option to have this rolled out and tested and then make this the default in chart release 3.x.

**Review by seanson — APPROVED** [review]

**Pull request merged**
