### PR TITLE
chore(argo-cd): Upgrade Argo CD to v2.8.6

### PR DESCRIPTION
**Pull request by tico24**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

https://github.com/argoproj/argo-cd/compare/v2.8.5...v2.8.6

### CODE REVIEW

**Review by mbevc1 — APPROVED** [review]

**Review by jmeridth — APPROVED** [review]

**Comment by mbevc1** [comment]
Seems there is an error with linting and one of the flags is not recognised:
```
>>> helm lint charts/argo-cd --values charts/argo-cd/ci/default-values.yaml --timeout 600s
Error: failed linting charts: failed processing charts
Error: unknown flag: --timeout
```

Has step been upgraded or not pinned?

**Comment by tico24** [comment]
Looks like it's moaning about the extra args in here: https://github.com/argoproj/argo-helm/blob/main/.github/configs/ct-lint.yaml

**Comment by tico24** [comment]
Timeout does indeed seem to no longer be a lint flag: https://helm.sh/docs/helm/helm_lint/

**Comment by mbevc1** [comment]
Let's remove it then :)

**Comment by tico24** [comment]
@jmeridth is doing so on my behalf. I'm stuck on mobile now until tomorrow.

**Comment by tico24** [comment]
Thanks @jmeridth - we are getting closer!

**Pull request merged**
