### PR TITLE
feat(argo-workflows): Allow to add custom artifact repository

### PR DESCRIPTION
**Pull request by maxkochubey**
Sometimes users need to add some custom type of artifacts repo like self-hosted Artifactory.

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @maxkochubey , thank you for your contribution!
will you please fix failed CI and conflicts ?

**Comment by maxkochubey** [comment]
> Hi @maxkochubey , thank you for your contribution! will you please fix failed CI and conflicts ?

Sure, will do!

**Comment by maxkochubey** [comment]
Hi @yu-croco - looks to be ok for now, I've checked to run `helm-docs` container locally without any issues.

**Review by yu-croco — APPROVED** [review]
LGTM!

**Pull request merged**
