### PR TITLE
feat(argo-workflows): Add support for Persistence Postgres SSL certificate if ssl is enabled

### PR DESCRIPTION
**Pull request by reddymh**
Signed-off-by: Rajshekar Reddy <reddymh@gmail.com>

Fixes https://github.com/argoproj/argo-helm/issues/1806

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by vladlosev** [comment]
Which specific change in this PR will allow the Postrges client certificate authentication?

**Comment by reddymh** [comment]
> Which specific change in this PR will allow the Postrges client certificate authentication?

https://github.com/argoproj/argo-workflows/pull/10300/files#diff-2d09762802d8f619a706e3469bbca56cfed83ddcafb5d9be0f1992367110e5f3

**Comment by jmeridth** [comment]
@reddymh I'm still confused also.  Linking to another PR does not explain how the current change in this PR will allow the Postrges client certificate authentication like @vladlosev is asking.

**Comment by reddymh** [comment]
> @reddymh I'm still confused also. Linking to another PR does not explain how the current change in this PR will allow the Postrges client certificate authentication like @vladlosev is asking.

postgres client tls certificate is passed via argo workflow configmap(which is read from helm value file) by specifying tls secret name and key in which the argo workflow controller and server is using currently.

**Comment by vladlosev** [comment]
I see what you are trying to do now and have a couple of comments on the PR. First, the original PR at https://github.com/argoproj/argo-workflows/pull/10300 has some issues. Resolving them will affect this one, so we may want to hold off on this one until that one is merged.

Second, setting `readOnlyRootFilesystem` to false by default is not a good [security practice](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#configure-your-images-with-read-only-root-file-system). Only a small subset of Argo users will be employing SSL authentication for PostreSQL but everyone will be negatively by this change. It is much better to add a comment in `values.yaml` explaining chat additional configuration changes must be done for the SSL auth to work. Having said that, resetting `readOnlyRootFilesystem` is not required even for the SSL auth users. Instead, they should create an `emptyDir` volume and mount it into the container. Also note that write-enabling the certificate directory has to be done for both workflow controller and server as they both access PostgreSQL databases.

**Comment by reddymh** [comment]
> I see what you are trying to do now and have a couple of comments on the PR. First, the original PR at [argoproj/argo-workflows#10300](https://github.com/argoproj/argo-workflows/pull/10300) has some issues. Resolving them will affect this one, so we may want to hold off on this one until that one is merged.
> 
> Second, setting `readOnlyRootFilesystem` to false by default is not a good [security practice](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#configure-your-images-with-read-only-root-file-system). Only a small subset of Argo users will be employing SSL authentication for PostreSQL but everyone will be negatively by this change. It is much better to add a comment in `values.yaml` explaining chat additional configuration changes must be done for the SSL auth to work. Having said that, resetting `readOnlyRootFilesystem` is not required even for the SSL auth users. Instead, they should create an `emptyDir` volume and mount it into the container. Also note that write-enabling the certificate directory has to be done for both workflow controller and server as they both access PostgreSQL databases.

yes you are right .I will add comment on readonlyfilesystem should be false when you enable ssl and even I am planning to mount tls secret on argo server and argo controller and configure the volume mount which is useful for both deployment object as well as postgres ssl certificate path.

**Comment by reddymh** [comment]
> I see what you are trying to do now and have a couple of comments on the PR. First, the original PR at [argoproj/argo-workflows#10300](https://github.com/argoproj/argo-workflows/pull/10300) has some issues. Resolving them will affect this one, so we may want to hold off on this one until that one is merged.
> 
> Second, setting `readOnlyRootFilesystem` to false by default is not a good [security practice](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#configure-your-images-with-read-only-root-file-system). Only a small subset of Argo users will be employing SSL authentication for PostreSQL but everyone will be negatively by this change. It is much better to add a comment in `values.yaml` explaining chat additional configuration changes must be done for the SSL auth to work. Having said that, resetting `readOnlyRootFilesystem` is not required even for the SSL auth users. Instead, they should create an `emptyDir` volume and mount it into the container. Also note that write-enabling the certificate directory has to be done for both workflow controller and server as they both access PostgreSQL databases.

@vladlosev  PR [argoproj/argo-workflows#10300](https://github.com/argoproj/argo-workflows/pull/10300)  has been successfully merged.
Could you please review and approve the PR?

**Comment by vladlosev** [comment]
I think it makes sense to wait until https://github.com/argoproj/argo-workflows/pull/10300 is released to commit this change. People will see it and may try it out. Until https://github.com/argoproj/argo-workflows/pull/10300 is released and the chart is updated to install that release, they will fail to see any results and are likely to open issues against the chart asking why it does not work.

**Comment by jmeridth** [comment]
Looks like https://github.com/argoproj/argo-workflows/pull/10300 was merged then reverted with https://github.com/argoproj/argo-workflows/pull/10736 so looks like upstream still trying to figure this out.

**Pull request closed without merging**
