### PR TITLE
feat(argo-rollouts): Add notification secret and configmap

### PR DESCRIPTION
**Pull request by ianmuge**
Fixing the error on the Argo rollouts controller by bootstrapping the notifications configmap and secret

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by ianmuge** [comment]
@mkilchhofer could you please help review this?

**Review by mkilchhofer — COMMENTED** [review]
Hi @ianmuge, Thanks for your contribution. I don't use rollouts and I can only review it from the chart side.

It looks okay. Things to think about:
- Bumping the minor chart version as it adds a feature
- Reusing the structure below the key `notifications` of the argocd-notification chart: https://github.com/argoproj/argo-helm/blob/master/charts/argocd-notifications/templates/configmap.yaml

**Comment by ianmuge** [comment]
Made the mistake of updating the branch with a merge commit, I can raise a New PR if this is a problem

**Comment by mbevc1** [comment]
Hm, seems there is more in this PR than intended :thinking:  - some ArgoCD chart changes?

**Comment by mkilchhofer** [comment]
> Hm, seems there is more in this PR than intended 🤔 - some ArgoCD chart changes?

I did a cleanup and force-pushed to the authors repo ;-). Will now have a look into the changes

**Comment by mkilchhofer** [comment]
I implemented a proposal in a similar way the argocd-notification chart does.

Could you review if this also fit for you @ianmuge ?

**Review by ianmuge — COMMENTED** [review]
This is perfect, highly appreciated!🙂

**Comment by mkilchhofer** [comment]
Cool :-)

@mbevc1 could we have your 👀 also to not approve my own changes? 😉

**Review by mkilchhofer — APPROVED** [review]

**Review by mbevc1 — APPROVED** [review]
LGTM

**Pull request merged**
