### PR TITLE
chore(argo-rollouts): Upgrade argo-rollouts to 1.4.0

### LINKED ISSUE #1763: Add: Helm Chart for argo-rollouts Release Version 1.4.0
### Is your feature request related to a problem?

Hi,

We are periodically upgrading our Infrastructure component to latest version -1. We can see that a new release of argo-rollouts for version 1.4.0 is released [here](https://github.com/argoproj/argo-rollouts/releases/tag/v1.4.0)

Requesting a feature to upgrade the chart to version 1.4.0.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

A new chart for version 1.4.0

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jmeridth**
Fixes #1763

Signed-off-by: jmeridth <jmeridth@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by alonbehaim** [comment]
> Just getting started on this. Handled CRD changes. Looking if `values.yaml` needs to expose some toggles and updating the templates. @saurabhvagrawal @alonbehaim was there anything in particular you were looking for with this update that we may need to make dynamic in the templated manifests (since you are both on #1763)?

Nothing special from my side, except of getting the Argo Rollout latest version with all recent fixes.

Thanks!

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Almost LGTM... Went through the changes here
https://github.com/argoproj/argo-rollouts/compare/v1.3.2...v1.4.0

Only one small nit is missing for the dashboard:
image

**Comment by jmeridth** [comment]
@mkilchhofer thank you for catching those.  There was also a section on `traefik.containo.us` apiGroup [that needed to be added](https://github.com/argoproj/argo-rollouts/compare/v1.3.2...v1.4.0#diff-61dcdccfff46893a12d8ac0b932049082c1cd27a57715e108917d71479759b3bR224-R239) in the clusterRole, from a previous upgrade.

I'm going to go through each file again and do a diff to make sure I get everything.

**Review by mkilchhofer — APPROVED** [review]
LGTM

**Pull request merged**
