### PR TITLE
feat(argo-workflows): update to Argo Workflows version 3.3.2

### LINKED ISSUE #1171: Argo-WF: chart 0.13.0 cannot deploy argo-wf v3.3.0
### Describe the bug

```
E0315 09:03:10.758806       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "secrets" in API group "" at the cluster scope
```

### Related helm chart

argo-workflows

### To Reproduce

Point `image.tag: v3.3.0` for executor, controller, 

### Expected behavior

Deployment gets healthy

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by irasnyd**
* Add WorkflowTaskResult CRD
* Add associated permissions to Workflow Controller Role

Fixes #1171

Signed-off-by: Ira W. Snyder <ira@descarteslabs.com>

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
I diffed argo-workflows manually using:

```console
$ git diff --numstat v3.2.9..v3.3.1 manifests/base/crds/minimal
425     0       manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml
2       0       manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
1       0       manifests/base/crds/minimal/kustomization.yaml
```

```diff
$ git diff v3.2.9..v3.3.1 manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
diff --git a/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml b/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
index 2d3c2dfa3..22cf52b19 100644
--- a/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
+++ b/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
@@ -37,3 +37,5 @@ spec:
         type: object
     served: true
     storage: true
+    subresources:
+      status: {}
```

Let's sync this also

**Comment by irasnyd** [comment]
Hi @mkilchhofer, thank you for the review. 😁 

I have added this change to the PR:

https://github.com/argoproj/argo-helm/pull/1214/files#diff-21c22022eb81f84a05e9cc96d4b513450a2a2cd855a1f7a3058a149ef37ecc3aR40-R41

```diff
$ git diff v3.2.9..v3.3.1 manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
diff --git a/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml b/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
index 2d3c2dfa3..22cf52b19 100644
--- a/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
+++ b/manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml
@@ -37,3 +37,5 @@ spec:
         type: object
     served: true
     storage: true
+    subresources:
+      status: {}
```

I don't know where to make this update. The `argo-helm/charts/argo-workflows` chart is very different from the upstream YAML in relation to `secrets` RBAC. Can you help me figure out where to make the update you're requesting?

```diff
$ git diff v3.2.9..v3.3.1 manifests/cluster-install/
diff --git a/manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml b/manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml
index f954115b0..74e7849f9 100644
--- a/manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml
+++ b/manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml
@@ -18,6 +18,8 @@ rules:
     verbs:
       - get
       - create
+      - list
+      - watch
   - apiGroups:
       - ""
     resources:
@@ -44,6 +46,7 @@ rules:
     verbs:
       - get
       - list
+      - watch
   - apiGroups:
       - argoproj.io
     resources:
```

And finally, I think this section is already present in the PR:

* PVC updates -- https://github.com/argoproj/argo-helm/pull/1214/files#diff-73770c8bd1dd7af5072c013798e9cbb5d897d59e2a16532bb9babf336ee05846R38-R43
* Workflow Task Results updates -- https://github.com/argoproj/argo-helm/pull/1214/files#diff-73770c8bd1dd7af5072c013798e9cbb5d897d59e2a16532bb9babf336ee05846R68-R76

```diff
diff --git a/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml b/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
index da6421441..3d6b5a395 100644
--- a/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
+++ b/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
@@ -28,8 +28,10 @@ rules:
   - ""
   resources:
   - persistentvolumeclaims
+  - persistentvolumeclaims/finalizers
   verbs:
   - create
+  - update
   - delete
   - get
 - apiGroups:
@@ -58,6 +60,14 @@ rules:
   - get
   - list
   - watch
+- apiGroups:
+    - argoproj.io
+  resources:
+    - workflowtaskresults
+  verbs:
+    - list
+    - watch
+    - deletecollection
 - apiGroups:
   - ""
   resources:
```

**Comment by mkilchhofer** [comment]
> I have added this change to the PR:

👍 

> I don't know where to make this update. The `argo-helm/charts/argo-workflows` chart is very different from the upstream YAML in relation to `secrets` RBAC. Can you help me figure out where to make the update you're requesting?

Yes, for me it's also hard to see where to put these changes :D. I don't use workflows so I can only review the "helm part".

**Comment by mkilchhofer** [comment]
@vladlosev WDYT the RBAC of the chart looks very very complicated and diverged from the upstream manifests.

I suggest to sync them to upstream (and drop a lot of the complicated conditionals) so we can easily sync back changes from the upstream releases.

**Comment by jmeridth** [comment]
@mkilchhofer @vladlosev can we help this PR in any way?  We'd love to see it get merged.  Thank you for all the hard work on it.  Cheers.

**Comment by vladlosev** [comment]
I agree these templates should be simplified. Bt the complexity was introduced in order to maintain backwards compatibility in the chart values. Dropping it would require breaking that backwards compatibility. Are we ready for that?

**Comment by jmeridth** [comment]
@vladlosev Since the helm chart versions different than the argo-workflows project, I'd suggest we can implement breaking changes and major version increase the helm chart notifying consumers.  What do you think?

I suggest this because we should probably remove the changes that were workarounds that are no longer needed.  I'm willing to help in any way. Cheers.

**Comment by jmeridth** [comment]
https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md#v332-2022-04-20 :) is what happens when we wait too long (joke)

**Comment by ShradhaKhard** [comment]
Looks, like we have v3.3.2 tag out there https://github.com/argoproj/argo-workflows/tree/v3.3.2. with so many other fixes https://github.com/argoproj/argo-workflows/commits/v3.3.2.

**Comment by jmeridth** [comment]
https://github.com/bitnami/charts/blob/master/bitnami/argo-workflows/Chart.yaml#L4 (nudge)

**Comment by jmeridth** [comment]
Thank you for bumping this to 3.3.2.

**Comment by jmeridth** [comment]
@mkilchhofer are you willing to remove your requested changes?

**Review by mkilchhofer — APPROVED** [review]
> I agree these templates should be simplified. Bt the complexity was introduced in order to maintain backwards compatibility in the chart values. Dropping it would require breaking that backwards compatibility. Are we ready for that?

Yea, let's simplify it in another PR and bump to 1.0.0 ;)

For me its perfectly fine if we move this PR forward and merge it.

**Pull request merged**
