### PR TITLE
feat(argo-rollouts): add deployment annotations for controller

### PR DESCRIPTION
**Pull request by mweberjc**
Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Review by mkilchhofer — COMMENTED** [review]
Almost LGTM.
Can you add that ability on the dashboard deployment as well? Just for consistency

**Comment by mweberjc** [comment]
@mkilchhofer done, thanks for catching this!

**Review by alanghartJC — APPROVED** [review]

**Comment by mkilchhofer** [comment]
Oh I see that this setting is in the global section in the argo-cd chart.

Can you put the `.Values.deploymentAnnotations` into a new global section (`.Values.global.deploymentAnnotations`), would be nice if we follow our standards :)

**Comment by mweberjc** [comment]
Can do, but I was conflicted about that, since `podAnnotations`, `crdAnnotations`, etc. are also essentially global, but live at the top-level.  Should we duplicate them into `global` as well?
```
./argo-rollouts/templates/controller/deployment.yaml:      {{- with (mergeOverwrite (deepCopy .Values.podAnnotations) .Values.controller.podAnnotations) }}
./argo-rollouts/templates/dashboard/deployment.yaml:      {{- with (mergeOverwrite (deepCopy .Values.podAnnotations) .Values.dashboard.podAnnotations) }}
```

**Comment by mkilchhofer** [comment]
Let's start the global section with the newly added feature. We can harmonize all related settings in a later PR with a new major version of the chart :-)

**Review by mkilchhofer — APPROVED** [review]

**Review by yu-croco — APPROVED** [review]

**Pull request merged**
