### PR TITLE
docs(argo-cd): Update README and remove template deps

### LINKED ISSUE #1257: Docs: Remove files version dependency
### Describe the bug

When we open a new PR it will require constance docs regeneration due dependency on raw file paths. We should remove this as it pollutes PRs with unrelated changes.

### Related helm chart

argo-cd

### To Reproduce

1. Create a new PR with changes unrelated to doc changes
2. Need to regenerate docs to match latest version for file paths: https://github.com/argoproj/argo-helm/pull/1253/files#diff-9b2b8960b2091a28395a78f3f4b76c4310b39062f6602f9a0575a27ed890f904R92-R95

### Expected behavior

We should be using reference to a default branch, i.e. https://raw.githubusercontent.com/argoproj/argo-helm/master/charts/argo-cd/crds/crd-extension.yaml to avoid constant path flap.

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbevc1**
Note on DCO:

Closes #1257

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Yeah, this already annoyed me😅
Another possibility is to mention a placeholder instead of `master`

**Comment by mbevc1** [comment]
We are already using `master` elsewhere, but what did you have in mind as a placeholder?

**Comment by mkilchhofer** [comment]
> We are already using `master` elsewhere, but what did you have in mind as a placeholder?

I almost didn't find it anymore. In the old AppSet chart we had this:

> ## Notes on CRD Installation
> 
> Some users would prefer to install the CRDs _outside_ of the chart. You can disable the CRD installation of this chart by using `--skip-crds` when installing the chart.
> 
> You then can install the CRDs manually from `crds` folder or via the manifests from the upstream project repo:
> 
> ```console
> kubectl apply -k https://github.com/argoproj-labs/applicationset.git/manifests/crds?ref=<appVersion>
> 
> # Eg. version v0.1.0
> kubectl apply -k https://github.com/argoproj-labs/applicationset.git/manifests/crds?ref=v0.1.0
> ```

An option would be to "redirect" the users to the upstream repository with the Kustomize manifests. All projects have a directory only containing the CRDs.

IMO we should standardize this message across all charts with CRDs not living in the `/templates/` directory of a chart (like argo-rollouts does).

**Comment by mbevc1** [comment]
Yeah, agree CRDs folder should be following upstream recommendation and be in the root folder of the chart.

Sure, I'll amend this to reference upstream CRDs folder :+1:

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
