### PR TITLE
chore(argo-workflows): Upgrade Argo Workflows to v3.6.0

### PR DESCRIPTION
**Pull request by yu-croco**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
😮‍💨 

>Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.argo-workflows-9knmn2ard5.v1" is invalid: data: Too long: must have at most 1048576 bytes

https://github.com/argoproj/argo-helm/actions/runs/11847799319/job/33018184325?pr=3037

**Comment by mkilchhofer** [comment]
> 😮‍💨
> 
> > Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.argo-workflows-9knmn2ard5.v1" is invalid: data: Too long: must have at most 1048576 bytes
> 
> https://github.com/argoproj/argo-helm/actions/runs/11847799319/job/33018184325?pr=3037

Sh*t. Are we really there now? The chart is too big for the 1M Secret limit 😢

**Comment by tico24** [comment]
So... running `ct install --config ../../.github/configs/ct-install.yaml --charts .` locally and it works fine. So this might be a GHA thing, or we've just got unlucky twice?

**Comment by vladlosev** [comment]
> Sh*t. Are we really there now? The chart is too big for the 1M Secret limit 😢

Now I understand why Helm decided to deal with CRDs the way it did.

**Comment by kunalmehta-eve** [comment]
@yu-croco Hey, did you get any chance to look at this release bump?

**Review by tico24 — APPROVED** [review]

**Comment by jmeridth** [comment]
> @yu-croco Hey, did you get any chance to look at this release bump?

We are working on it. Thank you for your patience

**Review by jmeridth — APPROVED** [review]

**Pull request merged**
