### PR TITLE
feat(argo-rollouts): add labels to crd to identify the rollout crds

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang <hui.kang@salesforce.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by huikang** [comment]
In certain cases, we need to delete the crds by their lables, the PR adds labels to the argo-rollouts crds.

@jessesuen , could you help take a look at this one? Thanks.

**Comment by jessesuen** [comment]
Aren't you supposed to increment Chart version?

**Comment by huikang** [comment]
> Aren't you supposed to increment Chart version?

Sorry, I forgot to do that. The PR has been updated.

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
@huikang can you rebase on master?

**Comment by huikang** [comment]
> @huikang can you rebase on master?

Done.

**Pull request merged**
