### PR TITLE
chore(github): Use Makefile instead of scripts

### PR DESCRIPTION
**Pull request by oliverbaehler**
@mkilchhofer what you think?

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Since I am not very familiar with Makefiles, I do not push this idea forward.
For me, Makefiles are harder to read ;-)

I'd like to hear on others. @jmeridth , @mbevc1 , @yann-soubeyrand , @yu-croco , @pdrastil WDYT?

**Comment by jmeridth** [comment]
I'm bias towards Makefiles, but I agree with @mkilchhofer's perspective of them being harder to read.  Understanding variable scope/knowing that each line is run in its own shell/etc are "quirks" that unexperienced contributors may have issues with re: Makefiles.

I'd still vote for a Makefile but look forward to other's inputs on this.

If this moves forward @oliverbaehler, the `helm-docs.sh` file is mentioned in the argo-events helm chart [`README.md`](https://cs.github.com/argoproj/argo-helm/blob/5b6cb2678a4558c39100084c7c0e8f5dd58de430/charts/argo-events/README.md#L17) and [`REAMDE.md.gotmpl`](https://cs.github.com/argoproj/argo-helm/blob/5b6cb2678a4558c39100084c7c0e8f5dd58de430/charts/argo-events/README.md.gotmpl#L17) files also. Don't know if it should be but want you to be aware.

**Comment by mbevc1** [comment]
I'm probably also slightly biased towards Makefile, but I don't have strong preference for either in this case as it doesn't seem to add much value :shrug: . If we decide to go for Makefile, looks like it missing dropping to privileges when running `docker` and `-u $(id -u)` is missing?

**Comment by pdrastil** [comment]
I'm also slightly biased towards Makefile which is simple to use from user perspective. I would be careful about formatting of the file because Makefile is tab sensitive if I remember correctly and finding bugs in whitespace is not fun during code review.

**Comment by yu-croco** [comment]
In addition to my poor experience to Makefile, it's happy for me to keep using ShellScript in the aspect of the current ShellScript quantity... 😇

**Pull request closed without merging**
