### PR TITLE
feat: Allow argo-cd server service port names to be configured.

### PR DESCRIPTION
**Pull request by Quarky9**
feat: Allows to route traffic via istio to split gRPC from http

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by spencergilbert** [comment]
@Quarky9 would we need this for any of the components?

**Comment by Quarky9** [comment]
> @Quarky9 would we need this for any of the components?

The only thing being exposed outside of a cluster is the server API normally so I would say not really.

Added the Istio part of my wrapper chart to show the use-case.
With this I am able to use the cli as well as the UI without having to add `--grpc-web` to cli calls.
```
{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server
  namespace: argocd
spec:
  gateways:
  - {{ .Values.istio.gateway }}
  hosts:
  - {{ .Values.argocd.server.config.url }}
  http:
  - name: grpc
    match:
    - headers:
        user-agent:
          prefix: argocd-client
    route:
    - destination:
        host: {{ .Release.Name }}-argocd-server
        port:
          number: 443
  - name: http
    route:
    - destination:
        host: {{ .Release.Name }}-argocd-server
        port:
          number: 80
{{- end }}```

**Comment by spencergilbert** [comment]
It's been a while since I looked at getting argocd working in an istio service mesh - remember having to fiddle with a few things to get things running. @Quarky9 can you resolve the `This branch is out-of-date with the base branch`?

**Comment by Quarky9** [comment]
Updated branch / PR.

**Comment by spencergilbert** [comment]
:thinking: @seanson is semantic pr upset because `Feat` is capitalized here? or am I missing something obvious?

**Comment by spencergilbert** [comment]
_i cant even_ :facepalm:

**Pull request merged**
