### PR TITLE
feat(argo-cd): Upgrade Argo CD to 2.8.0

### PR DESCRIPTION
**Pull request by pdrastil**
Initial draft for 2.8.0 release.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by venkatamutyala** [comment]
@pdrastil 2.8.0 dropped <30mins ago. (:

:shipit:🚀🌕

**Comment by mubarak-j** [comment]
in v2.8, gzip compression is enabled by default https://github.com/argoproj/argo-helm/blob/eae0bdd87117c2eb5e4f666196b6886f13b3f999/charts/argo-cd/values.yaml#L256

**Review by yu-croco — APPROVED** [review]
🚀

**Review by mkilchhofer — APPROVED** [review]
🎉

**Pull request merged**
