### PR TITLE
fix: Use GKEBackendConfig when enabled

### PR DESCRIPTION
**Pull request by redbaron**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

### CODE REVIEW

**Comment by spencergilbert** [comment]
@redbaron I haven't used GKE's backendconfig before, looking at the docs they're setting some port information as well. Is that not necessary?

**Comment by redbaron** [comment]
> @redbaron I haven't used GKE's backendconfig before, looking at the docs they're setting some port information as well. Is that not necessary?

It is possible to specify backend config for each port of the service. If they don't require different configurations, `default` works for all ports.

**Comment by seanson** [comment]
@redbaron  - Is this PR ready to go? If so, could you move it from "WIP/Draft" status?

**Comment by alexec** [comment]
Stale.

**Pull request closed without merging**
