### PR TITLE
feat(argo-cd): Always install applicationset crd

### PR DESCRIPTION
**Pull request by ebuildy**
ApplicationSet is required by argocd-server, cannot be "opt-out".

If ApplicationSet CRD is not installed, we see lot of errors:

```
W0507 19:44:33.469804 7 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: failed to list *v1alpha1.ApplicationSet: the server could not find the requested resource (get applicationsets.argoproj.io)
E0507 19:44:33.469828 7 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ApplicationSet: failed to list *v1alpha1.ApplicationSet: the server could not find the requested resource (get applicationsets.argoproj.io)
```

Relate:
- https://github.com/argoproj/argo-cd/pull/15432

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by pdrastil** [comment]
@mkilchhofer @yu-croco verified that error is there - should we drop `enabled` in appset controller and always deploy it?

**Comment by pdrastil** [comment]
@yu-croco - The CRD should be always enabled but it seems that AppSet is part of "core" as non-optional component in upstream. https://github.com/argoproj/argo-cd/blob/master/manifests/core-install/kustomization.yaml

**Comment by yu-croco** [comment]
@pdrastil 
> it seems that AppSet is part of "core" as non-optional component in upstream. https://github.com/argoproj/argo-cd/blob/master/manifests/core-install/kustomization.yaml

Thank you for pointing out. 👀 

>should we drop enabled in appset controller and always deploy it?

Ah now I understand what I misunderstood. 🙈 
I think we should remove `. Values.applicationSet.enabled`  attribute and make appSet deploy anytime, not only from `charts/argo-cd/templates/crds/crd-applicationset.yaml` . 🤔

**Comment by pdrastil** [comment]
@yu-croco yes - question was if we want to align with upstream and make this component mandatory

**Comment by mkilchhofer** [comment]
> @yu-croco yes - question was if we want to align with upstream and make this component mandatory

I am okay with both approaches. We can accept this PR and make it mandatory in another PR in the future?

**Comment by yu-croco** [comment]
Ah yes, we don't need to finish at once  🙈  , I agree with @mkilchhofer

**Comment by yu-croco** [comment]
Hi @ebuildy , can you please update changelog (remove old one and add new one) ? 🙋 
-> https://github.com/argoproj/argo-helm/pull/2682/files#diff-16f38cd1a4674cb682ac9f015fbc1c1ff552f024a8f791c16de0de21a1f65771R28-R30

>I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).

**Review by yu-croco — APPROVED** [review]
Thank you for your contribution. LGTM.

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
