### PR TITLE
feat(argo-cd): Truncate version labels to 63 characters

### PR DESCRIPTION
**Pull request by sathieu**
Allow to use digests.
https://github.com/argoproj/argo-helm/issues/417

Before this PR, a `values.yaml` like [this](https://gitlab.com/kubitus-project/kubitus-installer/-/jobs/2705596962#L8030):

```yaml
argo-cd:
  global:
    image:
      repository:  "quay.io/argoproj/argocd"
      tag: "v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c5725fe4052681950dc"

  dex:
    image:
      repository:  "ghcr.io/dexidp/dex"
      tag: "v2.32.0@sha256:85481bc46e04163ad0f2b6a003aef441ad324ffd48e78e5076c166b308c4f5fe"

  redis:
    image:
      repository:  "redis"
      tag: "7.0.2-alpine@sha256"
```

Fails [with](https://gitlab.com/kubitus-project/kubitus-installer/-/jobs/2705596962#L8167):

```
Error: Deployment.apps "argocd-redis" is invalid: [metadata.labels: Invalid value: "7.0.2-alpine@sha256": a valid label must be an empty string or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'',  or ''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?''), spec.template.labels: Invalid value: "7.0.2-alpine@sha256": a valid label must be an empty string or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'',  or ''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'')]
```

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Not sure if we should implement only a workaround for the label issue or if we want to properly support digests like my proposal in the past:
https://github.com/argoproj/argo-helm/pull/643

**Comment by sathieu** [comment]
@mkilchhofer I've seen PR #643, but I want to keep the version and the digest (i.e. I want `image: quay.io/argoproj/argocd:v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c5725fe4052681950dc` and not `image: quay.io/argoproj/argocd@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c5725fe4052681950dc`)

This is a common practice to use version@digest as tag value, and this is what works with `helm create` .

Inputs @arul-gupta @sarahhenkens

**Comment by sathieu** [comment]
@mkilchhofer I've rebased, please review again 🙏 .

**Review by mkilchhofer — APPROVED** [review]
👍

**Pull request merged**
