### PR TITLE
chore(argo-cd): Remove wildcard catch all ingress rule

### PR DESCRIPTION
**Pull request by pdrastil**
There will be multiple PRs for Ingress to decouple implementations for various controllers in attempt to make this piece more maintainable.

This PR removes ingress rule without specified hostname that acts as a global catch-all rule. It's usually not a good practice to have this in a cluster in first place as it can intercept traffic from another misconfigured application that is behind same Load balancer / IP. If we want to support this we can consider `defaultBackend` section if no hosts are provided, however from security perspective it's better to get 404 or 503 if administrator haven't configured default backend for any non-matching traffic.

Ref:
- https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend
- https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by jmeridth** [comment]
@pdrastil what do you think about making this a minor version update instead of patch as some people could be, maybe even unwittingly, be using the catch-all situation.  wdyt?

I approve the security best practice approach and getting it in.

**Comment by pdrastil** [comment]
@jmeridth Bumped. Also I would like to have your opinion on guard on top for of ingress. If no host is specified do we want to fail hard or do we want to silently skip rendering and let the user fix it troubleshoot why the ingress is not working.

**Comment by pdrastil** [comment]
I've added extraRules so it's still possibly to explicitly configure the catch-all rule if someone needs it.

**Comment by pdrastil** [comment]
Resolved via https://github.com/argoproj/argo-helm/pull/2407

**Pull request closed without merging**
