### PR TITLE
feat(argo-cd): Add ability to use an external redis instance

### LINKED ISSUE #1045: Use existing (managed) Redis for Argo CD
### Is your feature request related to a problem?

When I deploy the Argo CD HELM chart, I have the option to turn Redis off or on. I would like to be able to use existing Redis - my application already uses managed Redis (AWS ElastiCache) and it seems unnecessary to run more than one Redis in that case.

### Related helm chart

argo-cd

### Describe the solution you'd like

It would be great if I could disable Redis deployment in `values.yaml` and configure host/port/... to an existing running Redis.

```yaml

redis:
  enabled: false

  host: foo-redis.bar.0001.euw1.cache.amazonaws.com
  port: 6379
  ...
  ...

redis-ha:
  enabled: false

```

### Describe alternatives you've considered

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by mkilchhofer**
Resolves #1045

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Hi @mbevc1
WDYT about this PR? Do you have time to review it? ;)

**Comment by mbevc1** [comment]
Hey, sure. I'll give it a look later. Would you mind rebasing please?

**Comment by mkilchhofer** [comment]
Cool :) Rebase done

**Review by mbevc1 — APPROVED** [review]
LGTM

**Pull request merged**
