### PR TITLE
fix(argo-workflows): Add missing WorkflowTasksets RBAC to controller

### LINKED ISSUE #997: Argo Workflows controller RBAC missing workflowtasksets resources
### Describe the bug

The workflow controller when run at the cluster scope is missing the ability to watch or list `WorkflowTaskSets`. This may also be the case namespaced.

### Related helm chart

argo-workflows

### To Reproduce

Deploy the latest v0.8.0 Helm Chart for Argo Workflows. View the logs of the workflows controller.

### Expected behavior

The workflow controller can watch `WorkflowTaskSets` as well as list them. I would expect to see `workflowtasksets` and possibly `workflowtasksets/finalizers` in `charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml`.

### Screenshots

_No response_

### Additional context

Here is one of the lines in the workflow controller logs:

```
pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden:  │
│ User "system:serviceaccount:argons:argo-workflows-tst-workflow-controller" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
```

Note, my Helm release is named `argo-workflows-tst`.

### PR DESCRIPTION
**Pull request by paulaylingdev**
Closes #997 

Signed-off-by: Paul Ayling <paulayling.dev@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by paulaylingdev** [comment]
Think this catches all the missed changes between v3.1.15 and v3.2.0:

`git diff v3.1.15..v3.2.0 manifests/install.yaml`

```diff
diff --git a/manifests/install.yaml b/manifests/install.yaml
index f75279529..d6d909475 100644
--- a/manifests/install.yaml
+++ b/manifests/install.yaml
@@ -166,6 +166,46 @@ spec:
 ---
 apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
+metadata:
+  name: workflowtasksets.argoproj.io
+spec:
+  group: argoproj.io
+  names:
+    kind: WorkflowTaskSet
+    listKind: WorkflowTaskSetList
+    plural: workflowtasksets
+    shortNames:
+    - wfts
+    singular: workflowtaskset
+  scope: Namespaced
+  versions:
+  - name: v1alpha1
+    schema:
+      openAPIV3Schema:
+        properties:
+          apiVersion:
+            type: string
+          kind:
+            type: string
+          metadata:
+            type: object
+          spec:
+            type: object
+            x-kubernetes-map-type: atomic
+            x-kubernetes-preserve-unknown-fields: true
+          status:
+            type: object
+            x-kubernetes-map-type: atomic
+            x-kubernetes-preserve-unknown-fields: true
+        required:
+        - metadata
+        - spec
+        type: object
+    served: true
+    storage: true
+---
+apiVersion: apiextensions.k8s.io/v1
+kind: CustomResourceDefinition
 metadata:
   name: workflowtemplates.argoproj.io
 spec:
@@ -250,6 +290,8 @@ rules:
   - cronworkflows/finalizers
   - clusterworkflowtemplates
   - clusterworkflowtemplates/finalizers
+  - workflowtasksets
+  - workflowtasksets/finalizers
   verbs:
   - create
   - delete
@@ -354,6 +396,8 @@ rules:
   resources:
   - workflows
   - workflows/finalizers
+  - workflowtasksets
+  - workflowtasksets/finalizers
   verbs:
   - get
   - list
@@ -559,7 +603,7 @@ spec:
       containers:
       - args:
         - server
-        image: docker.io/argoproj/argocli:latest
+        image: quay.io/argoproj/argocli:latest
         name: argo-server
         ports:
         - containerPort: 2746
@@ -605,7 +649,7 @@ spec:
         - --configmap
         - workflow-controller-configmap
         - --executor-image
-        - argoproj/argoexec:latest
+        - quay.io/argoproj/argoexec:latest
         command:
         - workflow-controller
         env:
@@ -614,7 +658,7 @@ spec:
             fieldRef:
               apiVersion: v1
               fieldPath: metadata.name
-        image: docker.io/argoproj/workflow-controller:latest
+        image: quay.io/argoproj/workflow-controller:latest
         livenessProbe:
           failureThreshold: 3
           httpGet:
```

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Thanks for your contribution. This is also missing in the admin aggregate-role:
[workflowtasksets](https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml#L66-L76)

**Review by mkilchhofer — APPROVED** [review]
👍

**Comment by paulaylingdev** [comment]
> Thanks for your contribution. This is also missing in the admin aggregate-role: [workflowtasksets](https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml#L66-L76)

Thanks I wasn't too familiar with the aggregate roles so wasn't sure. That should be added now

**Pull request merged**
