### PR TITLE
feat(argo-workflows): Add mainContainer config in configmap

### PR DESCRIPTION
**Pull request by prateekkhera92**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/main/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by jmeridth** [comment]
@prateekkhera92 please note this comment on the argo-workflows project [here](https://github.com/argoproj/argo-workflows/blob/73ea7c72c99a073dbe3ec0a420e112945916fb94/docs/workflow-controller-configmap.yaml#L194).  In <= v3.3 only `resources` are supported.  With >= v3.4 all are supported (including `securityContext`)

Since our chart is on [v3.3.6](https://github.com/argoproj/argo-helm/blob/66638628b07bdd7312a8920b52390c93ddbba678/charts/argo-workflows/Chart.yaml#L6), only `resources` is supported.  Argo-workflows hasn't released v3.4+ yet so...don't know if this holds.  /cc @alexec can confirm (or another maintainer)

I also don't see `env` being supported.  It might be a meta attribute.  I'm validating.

**Review by jmeridth — APPROVED** [review]

**Comment by jmeridth** [comment]
@prateekkhera92 that's good enough for me.  thank you for testing.

**Comment by jmeridth** [comment]
Removed approval until all things pass :smile:

**Comment by jmeridth** [comment]
@prateekkhera92 because you're adding a new section to the README, you need to edit the README.md.gotmpl

**Comment by prateekkhera92** [comment]
@jmeridth - thanks, added my changes to README.md.gotmpl now. Could you help run the CI and approval :)

**Comment by prateekkhera92** [comment]
@jmeridth - are you aware why CI is failing? I am not sure..

**Comment by prateekkhera92** [comment]
@jmeridth - sorry, could you help in getting CI fixed? I'd really appreciate that.

**Comment by mkilchhofer** [comment]
I did the exclude operation for you :-)

**Review by mbevc1 — APPROVED** [review]

**Review by jmeridth — APPROVED** [review]

**Comment by prateekkhera92** [comment]
Thanks everyone :)

**Pull request merged**
