### PR TITLE
fix(argo-workflows): Moving CRDs to the Templates folder

### PR DESCRIPTION
**Pull request by christophercutajar**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

This PR is related to https://github.com/argoproj/argo-helm/issues/1430. This PR includes:
- Moving CRDs to the templates folder
- Adding `crds` variable in the `values.yaml

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by yu-croco** [comment]
I think we need to describe how to adopt existing CRDs, like https://github.com/argoproj/argo-helm/pull/1342 . 👀

**Comment by yu-croco** [comment]
I think this PR has breaking change for existing users, so we need to describe how to adopt existing CRDs, like https://github.com/argoproj/argo-helm/pull/1342 . 👀

argo-workflows does not have updating guid for now, like https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#upgrading , so I think we need to add this section on argo-workflow's README as well.

WDYT @stefansedich  @paguos @vladlosev @yann-soubeyrand @jmeridth  ? 🙋

**Review by jmeridth — CHANGES_REQUESTED** [review]
I'd like the conversation in #1430 to continue before we merge this.

**Comment by jmeridth** [comment]
This was completed with #1472

**Pull request closed without merging**
