### PR TITLE
feat: argocd-notifications 1.0.10 add podAnnotations

### PR DESCRIPTION
**Pull request by caugustus-ezcater**
This PR adds the ability to set arbitrary annotations on the deployment via `podAnnotations`. My use case was to add annotations that allow Datadog to scrape metrics from the pod.

Checklist:

* [X] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [X] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by caugustus-ezcater** [comment]
I'm not sure if i need to resolve the Semantic Pull Request failure / what the best solution is

**Comment by andyfeller** [comment]
hey @caugustus-ezcater !  sorry for the delayed follow up as its been a bad week personally.  Let me take a look as I'm honestly not familiar; possible it'd want to go from 1.0.9 to 1.1.0 but let's look

**Comment by andyfeller** [comment]
Source: https://github.com/zeke/semantic-pull-requests/tree/7a3fb32c91394d84ac560cf63db4b2c9b5a48660#how-it-works
> By default, only the PR title OR at least one commit message needs to have semantic prefix.

So we either need to:
1. `git commit --allow-empty -m "1.0.10: empty commit for semantic PR check"`
1. Change the PR title to allude to the semantic version change

**Comment by andyfeller** [comment]
Trying to look at old PRs to see how this worked then; https://github.com/argoproj/argo-helm/pull/416
Might be a more recent change but either suggestion is worth trying at least.

**Comment by andyfeller** [comment]
Failed semantic check wasn't a blocking check and unsure why it was an issue.  Will have to hit up @alexmt to see what's going on with that.  Thanks again @caugustus-ezcater !

**Pull request merged**
