### PR TITLE
fix(argo-workflows): move crds folder into templates folder

### LINKED ISSUE #1430: [Argo Workflows] CRDs are not deployed as part of the Helm Chart
### Describe the bug

Argo Workflow CRDs located in https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows/crds aren't deployed automatically.

### Related helm chart

argo-workflows

### Helm chart version

0.17.1

### To Reproduce

1. Add `argo-workflows` in the `requirements.yaml`

```
dependencies:
  - name: argo-workflows
    repository: "https://argoproj.github.io/argo-helm"
    version: 0.17.1
```

2.  Sample Values file and deploy

```
argo-workflows:
  workflow:
    serviceAccount:
      create: true
    rbac: 
      create: true
  controller:
    rbac:
      create: true
    serviceAccount: 
      create: true
```

3. Check the installed CRDs such as [argoproj.io_workflowtaskresults.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/crds/argoproj.io_workflowtaskresults.yaml) is not automatically installed

### Expected behavior

All CRDs should be installed

### Screenshots

```
kubectl get crds

NAME                                             CREATED AT
applications.argoproj.io                         2021-12-02T15:55:07Z
applicationsets.argoproj.io                      2022-01-10T19:51:08Z
appprojects.argoproj.io                          2021-12-02T15:55:08Z
backendconfigs.cloud.google.com                  2021-11-30T20:21:46Z
capacityrequests.internal.autoscaling.gke.io     2021-11-30T20:21:09Z
certificaterequests.cert-manager.io              2022-05-03T17:26:17Z
certificates.cert-manager.io                     2022-05-03T17:26:17Z
challenges.acme.cert-manager.io                  2022-05-03T17:26:17Z
clusterissuers.cert-manager.io                   2022-05-03T17:26:17Z
clusterworkflowtemplates.argoproj.io             2021-12-02T15:55:06Z
cronworkflows.argoproj.io                        2021-12-02T15:55:06Z
eventbus.argoproj.io                             2022-08-23T15:58:43Z
eventsources.argoproj.io                         2022-08-24T11:26:35Z
frontendconfigs.networking.gke.io                2021-11-30T20:21:46Z
issuers.cert-manager.io                          2022-05-03T17:26:17Z
managedcertificates.networking.gke.io            2021-11-30T20:21:13Z
orders.acme.cert-manager.io                      2022-05-03T17:26:17Z
sensors.argoproj.io                              2022-08-23T15:58:43Z
serviceattachments.networking.gke.io             2021-11-30T20:21:47Z
servicenetworkendpointgroups.networking.gke.io   2021-11-30T20:21:46Z
storagestates.migration.k8s.io                   2021-11-30T20:21:15Z
storageversionmigrations.migration.k8s.io        2021-11-30T20:21:15Z
updateinfos.nodemanagement.gke.io                2021-11-30T20:21:16Z
volumesnapshotclasses.snapshot.storage.k8s.io    2021-11-30T20:21:14Z
volumesnapshotcontents.snapshot.storage.k8s.io   2021-11-30T20:21:15Z
volumesnapshots.snapshot.storage.k8s.io          2021-11-30T20:21:15Z
workfloweventbindings.argoproj.io                2021-12-02T15:55:07Z
workflows.argoproj.io                            2021-12-02T15:55:08Z
workflowtemplates.argoproj.io                    2021-12-02T15:55:08Z
```

### Additional context

https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows/crds folder should be moved into the https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows/templates folder

### PR DESCRIPTION
**Pull request by jmeridth**
Fixes #1430 #1468

Due to multiple instances where new/changed CRDs for argo-workflows do not get installed/updated I believe it is time to move the crds folder into the templates folder like our other helm charts.

I'm aware helm 3 is supposed to handle the crds folder but it seems there are a few known issues currently [here](https://github.com/hashicorp/terraform-provider-helm/issues/944), [here](https://github.com/helm/helm/issues/11321) and [here](https://github.com/helm/helm/pull/11330) that show that may still need some work.

Signed-off-by: jmeridth <jmeridth@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by pdrastil — APPROVED** [review]

**Comment by yu-croco** [comment]
Hi @jmeridth, it's just FYI.
This one may help you for the CI error, I hope. 😄 
https://github.com/argoproj/argo-helm/pull/1342#issuecomment-1226871106

> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "clusterworkflowtemplates.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "argo-workflows-vaf1aanci5": current value is "argo-workflows-i20uxuhx8l"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "argo-workflows-vaf1aanci5": current value is "argo-workflows-i20uxuhx8l"

**Review by yu-croco — APPROVED** [review]
Thank you for investigating and improving! 🚀

**Comment by Transmitt0r** [comment]
This breaks using the Argo-workflows helmchart as a dependency for charts that create e.g. WorkflowTemplates. Do you know a way to work around this?

**Comment by jmeridth** [comment]
@Transmitt0r we are successfully using the latest version of the Argo-workflows helm chart as a sub chart and are creating and using workflowtemplates.

Can you please elaborate on your situation more? Maybe in a new issue or discussion?

**Comment by Transmitt0r** [comment]
@jmeridth sure, I think I have the same issue as #1447

**Comment by DingGGu** [comment]
It needs label and annotate existing crds.

```bash
for crd in "clusterworkflowtemplates.argoproj.io" "cronworkflows.argoproj.io" "workflowartifactgctasks.argoproj.io" "workfloweventbindings.argoproj.io" "workflows.argoproj.io" "workflowtaskresults.argoproj.io" "workflowtasksets.argoproj.io" "workflowtemplates.argoproj.io"; do
  kubectl label --overwrite crd $crd app.kubernetes.io/managed-by=Helm
  kubectl annotate --overwrite crd $crd meta.helm.sh/release-namespace=argo
  kubectl annotate --overwrite crd $crd meta.helm.sh/release-name=argo
done
```

**Pull request merged**
