### PR TITLE
docs(argocd-image-updater): adding google artifact registry to the list

### PR DESCRIPTION
**Pull request by Kripu77**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @Kripu77 , it looks that this PR has a lot of unnecessary diffs. 👀

**Comment by tico24** [comment]
Main branch just needed to be merged in. It looks much less horrifying now!

**Comment by tico24** [comment]
The latest version of the referenced documentation does not mention Google Artifcact Registry though: https://argocd-image-updater.readthedocs.io/en/latest/configuration/registries/

**Comment by yu-croco** [comment]
Hi @Kripu77 , can you give us the official info that argocd-image-updater supports `Google Artifact Registry` ?

> The latest version of the referenced documentation does not mention Google Artifcact Registry though: https://argocd-image-updater.readthedocs.io/en/latest/configuration/registries/

**Pull request closed without merging**
