### PR TITLE
fix: update CRDs

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Checklist:

* [X] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [X] I have signed the CLA and the build is green.
* [X] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by yann-soubeyrand** [comment]
This commit is inspired by https://github.com/helm/charts/commit/89b233eef6dbc1b6fac418bde3a5a6f4e14406d4#diff-e4d188f136b67765a471cbb46268cbd2.

**Comment by spencergilbert** [comment]
@yann-soubeyrand mind adding a quick description to the readme?

**Comment by yann-soubeyrand** [comment]
@spencergilbert unless I did a mistake, this PR should only update the CRDs (for Helm 2 and Helm 3) to be in sync with the version of Argo CD which is deployed. However, it doesn't touch anything else (in particular, the value to disable CRD creation when using Helm 2 is the same and should have the same effect). What aspect of this PR do you want me to describe?

**Comment by spencergilbert** [comment]
Isn't .Values.installCRDs a new value we can toggle?

**Comment by yann-soubeyrand** [comment]
No, this value was already there: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L8 ;-)

**Comment by spencergilbert** [comment]
Whoops, sorry about that @yann-soubeyrand - thanks for the fix

**Comment by yann-soubeyrand** [comment]
@spencergilbert no problem ;-)

**Pull request merged**
