### PR TITLE
fix(argo-cd): Add ServiceAccount for redis

### LINKED ISSUE #809: Can not create a service account for redis in argo-cd helm chart
**Describe the bug**
If i want to setup a service account for redis i have to select the redis-ha option. In a normal installation of argo-cd a service account for redis is automatically created. The default behavior for the helm chart should be the same.

**To Reproduce**
1. Install argo-cd like this: https://argo-cd.readthedocs.io/en/stable/getting_started/#1-install-argo-cd
2. Service account for redis is created
3. Install argo-cd via helm chart
4. No option to create a service account

**Expected behavior**
It should be possible to create a service account (role and role binding) via values.yaml the same way as for argocd-repo-server.

### PR DESCRIPTION
**Pull request by mkilchhofer**
Resolves #809

While here, I noticed that there might exist clashing ServiceAccount resources when the default names of `controller`, `dex`, `server` and `repoServer` are cleared. This is an edge case but its fixed now :-)

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
@alexec Does @mbevc1 have correct permissions? He's in the CODEOWNERS file but Github does not pick him up as a reviewer.

**Comment by mbevc1** [comment]
:thinking:

**Comment by mbevc1** [comment]
Seems I might need push access to the repo :thinking: 
https://github.com/isaacs/github/issues/989#issuecomment-320475904

**Review by davidkarlsen — APPROVED** [review]

**Comment by mkilchhofer** [comment]
> Seems I might need push access to the repo 🤔
> [isaacs/github#989 (comment)](https://github.com/isaacs/github/issues/989#issuecomment-320475904)

Created an issue for this (#829) so we can move on with this PR here and not forget to grant access for you.

**Comment by mbevc1** [comment]
Cheers @mkilchhofer :+1:

**Comment by chillum** [comment]
the changing of reposerver's and server's serviceaccount names is a breaking change (causing some existing configurations stopping working)

it would be nice if this was mentioned in the changelog.

**Comment by chillum** [comment]
also please note that this change violated this checkbox from the checklist:
> Any new values are backwards compatible and/or have sensible default.

a sudden renaming of service accounts is not a backwards-compatible change, it literally breaks existing configurations that depend on service account's names (like GKE clusters with WorkloadIdentity).

**Comment by mkilchhofer** [comment]
Hi @chillum,

Thanks for your attention. But these template functions are currently used as a default/fallback if someone override values to `nil` or `""` (empty string):

```yaml
controller:
  # (..)
  serviceAccount:
    create: true
    name: argocd-application-controller

dex:
  serviceAccount:
    create: true
    name: argocd-dex-server

server:
  serviceAccount:
    create: true
    name: argocd-server

repoServer:
  # (..)
  serviceAccount:
    create: false
    #  name: argocd-repo-server
```
Okay, I missed that the `repoServer`'s `name` parameter was only a comment. But for every other component, this template function does not change something as there are values set for the names.
Additional the repoServer normally does not need a serviceAccount as it does not talk to the K8s APIserver.

WDYT? Shall we file a PR to add some hints to the README or does my explanation make sense?

**Comment by chillum** [comment]
so, you changed the default reposerver's serviceaccount name from `argo-cd-argocd` to `argocd-repo-server` and don't think it deserves a mention in the changelog?

this change does break existing configurations, I've been debugging one today.

**Comment by mkilchhofer** [comment]
This change got at least 4 eyes before it got merged.

Please be constructive with your critique
--> what do you suggest to do now? The change did already happen.

Revert? Additional PR? Update the Changelog in Artifacthub?

**Comment by chillum** [comment]
if in previous versions you'd set just:
```yaml
repoServer:
  serviceAccount:
    create: true
```

the user would end up with following service accounts:
* argo-cd-argocd
* argocd-application-controller
* argocd-dex-server
* argocd-server

the 3.8.1 makes a different result:
* argocd-repo-server
* argocd-application-controller
* argocd-dex-server
* argocd-server

yeah, now it looks cleaner, but this is a breaking change. so I'd say the documentation on this had changed is a must. it's been only several hours since the release and first users already found this problem and I'd expect more to come.

revert? no for sure. we could rename the fallback `argocd-repo-server` account back to `argo-cd-argocd` (but keep the new name as comment), but it would introduce complexity. I'd say this depends whether we prefer sane defaults or backward compatibility, but both are important. frankly not sure how much users would be affected though, so I think I'd keep the new name. but documented it.

**Comment by mkilchhofer** [comment]
Added a draft PR to address this: https://github.com/argoproj/argo-helm/pull/830 Please let me know if this is sufficient for you :-)

**Comment by chillum** [comment]
yeah, that looks great, many thanks.
one more idea, if the point of 3.8.1 was ServiceAccount for Redis.

maybe we shouldn't set `redis.serviceAccount.name = ""` in the defaults (and uncomment the repo-server stuff to do this change even more prominent and obvious). they both fallback to defaults, but setting them explicitly in the defaults file (like the chart does with other service accounts) provides better observability: one can look at default `values.yaml` and read the service accounts' name just from there. or copy and edit.

**Comment by mkilchhofer** [comment]
Okay, but this would introduce the next breaking change 🙈 We'd better wait for the next breaking change and let the chart generate all the ServiceAccount names by default. WDYT?

I already think about another breaking change: Implement what was promised:
>### 2.10.x to 2.11.0
>
>The application controller is now available as a `StatefulSet` when the `controller.enableStatefulSet` flag is set to true. >Depending on your Helm deployment this may be a downtime or breaking change if enabled when using HA and will become the default in 3.x.

**Comment by chillum** [comment]
oh, yes, looked up the [redis naming template](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/_helpers.tpl#L44) and it's indeed complicated, so my proposal will be another breaking change. =)

**Pull request merged**
