### PR TITLE
fix(argo-cd): Update vulnerabile containers versions

### PR DESCRIPTION
**Pull request by goroi**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mbevc1** [comment]
Thank you for your contribution! Seems like upstream is still deploying with older images, i.e.e Redis: https://github.com/argoproj/argo-cd/blob/master/manifests/base/redis/argocd-redis-deployment.yaml#L24. Not sure we want to diverse from that in defaults, but you can still override images via values. @mkilchhofer what are your thoughts?

**Comment by mkilchhofer** [comment]
> Thank you for your contribution! Seems like upstream is still deploying with older images, i.e.e Redis: https://github.com/argoproj/argo-cd/blob/master/manifests/base/redis/argocd-redis-deployment.yaml#L24. Not sure we want to diverse from that in defaults, but you can still override images via values. @mkilchhofer what are your thoughts?

Yes I am torn between update or not. The initial intent was to be inline with the kustomize manifests:

> ## Synchronizing Changes from Original Repository
> In the original ArgoCD repository an manifests/install.yaml is generated using kustomize. It's the basis for the installation as described in the docs.
> 
> **When installing ArgoCD using this helm chart the user should have a similar experience and configuration rolled out.**

But we get new PRs which addresses vulnerabilities all the time. So I think we should accept them or make it clearer in the README.

**Comment by goroi** [comment]
Hi thank you for considering the proposed changes. Please let me know if I should raise a PR with the same changes in the kustomize manifests.

**Comment by mbevc1** [comment]
Upstream has updated Redis and app version which is addressed now in https://github.com/argoproj/argo-helm/pull/1102

**Comment by mbevc1** [comment]
This was addressed via #1102 . If you'd still like to make additional changes please feel free to open a new PR. Closing this outdated and stale PR. Thanks!

**Pull request closed without merging**
