### PR TITLE
fix(argo-cd): fixed typos in chart's README.md file

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Would you mind to bump the chart patch version? We need green lights from our CI system and we cannot get a successful build without bumping the chart version.

**Comment by developer-guy** [comment]
> Would you mind to bump the chart patch version? We need green lights from our CI system and we cannot get a successful build without bumping the chart version.

Thank you @mkilchhofer, of course, I am going to do that soon 👍

**Comment by mkilchhofer** [comment]
Hi @developer-guy again,
Could you reword your commit message to be compliant to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? If you want, you can use the same message as this PR has (I renamed it to be compliant).

**Comment by developer-guy** [comment]
> Hi @developer-guy again,
> Could you reword your commit message to be compliant to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? If you want, you can use the same message as this PR has (I renamed it to be compliant).

thank you @mkilchhofer 😋🙏

**Review by mkilchhofer — APPROVED** [review]
LGTM now :-) lets merge this.

**Comment by developer-guy** [comment]
> LGTM now :-) lets merge this.

thank you so much @mkilchhofer, it was a quite fun to work with you 🥳🙋🏻‍♂️

**Pull request merged**
