### PR TITLE
chore(argo-cd): Refactor and cleanup argo-cd chart

### PR DESCRIPTION
**Pull request by pdrastil**
Resolves:
- [x] https://github.com/argoproj/argo-helm/issues/802
- [x] https://github.com/argoproj/argo-helm/issues/1514

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] ~~Any new values are backwards compatible and/or have sensible default.~~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by pdrastil** [comment]
Making this PR as draft so @mkilchhofer @jmeridth can provide feedback / suggestions for extra refactoring.

**Comment by mkilchhofer** [comment]
I went through commit by commit and was thinking yeah, this commit makes sense on a green grass env. But with every commit I went through, I felt increasing pain for every existing customer of this helm chart.
From my side I do not promote this PR but maybe someone is really enthusiastic about it? @mbevc1  @davidkarlsen  @yu-croco WDYT?

There are very helpful things in it but IMHO it is really tooo big for existing environments and the risk to break something is endlessly high.

**Comment by mbevc1** [comment]
Agree @mkilchhofer ; my initial thought was also this is a huge PR, thus really hard to review based on number of changes it's imposing. I think it's going to be really hard to ensure it's not breaking things for existing users and also it's a huge cognitive overload going through it. I'd suggest splitting it up in smaller chunks and approach it this way.

**Comment by yu-croco** [comment]
I agree with @mkilchhofer too. It's a little too big diff for reviewing and users would have a hard time updating version..
As @mbevc1 mentioned, maybe PR in smaller chunks would be nice.

**Comment by jmeridth** [comment]
I agree with @mkilchhofer. The scope is too large for careful review and has the potential for users switching to it to be a quite painful experience. Excellent effort but maybe smaller chunks and an intermediate timeframe where have old and new.

**Comment by pdrastil** [comment]
@mkilchhofer OK - I will keep this in a draft mode and try to pull things out of this into non-breaking and breaking changes. As I was reviewing the code there are many things that do not work as they suppose to.

**Pull request closed without merging**
