### PR TITLE
Take certificate, route and ingress host from Argo CD server URL config

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Checklist:

* [ ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed the CLA and the build is green.
* [ ] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by yann-soubeyrand** [comment]
This PR is not ready yet, I opened it for discussion before finalizing it.

**Comment by seanson** [comment]
What's the primary driver for this change?

**Comment by yann-soubeyrand** [comment]
Since ingress host and path must be identical to the ones in Argo CD external URL for the latter to be reachable, we should not have separate settings for it. The same reasoning holds true for certificate domain and route host. This way we eliminate potential configuration errors (in addition to not having to repeat ourselves).

**Comment by yann-soubeyrand** [comment]
@seanson it also fixes the certificate which is broken at the time.

**Comment by seanson** [comment]
Certificate path fix is pending in #171 
I appreciate the effort but I'm going to reject this PR in preference to keeping things simple and explicit even if redundant. It doesn't look like any of the official Helm repo charts use `regexReplaceAll`, other than some dashboard name mangling in the Grafana chart.

**Pull request closed without merging**
