### PR TITLE
chore(argo-events): update argo-events to 1.3.0

### PR DESCRIPTION
**Pull request by rory-lamendola**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by alecrajeev — COMMENTED** [review]
Also should update the tag versions of sensorController, eventsourceController, and eventbusController to be 1.3.0

https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/values.yaml#L48
https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/values.yaml#L58
https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/values.yaml#L68

**Comment by alecrajeev** [comment]
To pass the Semantic Pull Request PR, may have to make the PR title and the latest commit be like this:
"chore(argo-events): update argo-events to 1.3.0"

**Review by alecrajeev — APPROVED** [review]
Thanks! I tested using 1.3.0 as the image tags and it was successful

**Comment by oliverbaehler** [comment]
Hi @rory-lamendola, Thanks for your contribution. In order for this to be reviewed I need you to sign off all your commits (https://docs.github.com/en/github/authenticating-to-github/signing-commits). And Pull the latest State from the master branch. Thanks :)

**Comment by oliverbaehler** [comment]
Resolved by #720

**Pull request closed without merging**
