### PR TITLE
feat(argo-events): Added support for extra k8s manifests

### PR DESCRIPTION
**Pull request by oterno**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by jmeridth — APPROVED** [review]

**Comment by jmeridth** [comment]
Only suggestion, but not a blocker, is to have an example in the new values.yaml section like the extraObjects in [argo-cd chart values.yaml](https://github.com/argoproj/argo-helm/blob/0578482bd69c2cf341e34893e916d638002d546d/charts/argo-cd/values.yaml#L431)

**Comment by oterno** [comment]
I added a value example as suggested

**Comment by vladlosev** [comment]
This feature opens a huge security hole in the project. It creates an opportunity for anyone with access to the chart values to write something like this:
```yaml
extraObjects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: imnotahackertool
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: imnotahackertool
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: imnotahackertool
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: joe@darkunderground.com
```
and take over the cluster.

**Comment by oterno** [comment]
This feature is not different from `extraObjects` in the values.yaml of [argo-cd](https://github.com/argoproj/argo-helm/blob/0578482bd69c2cf341e34893e916d638002d546d/charts/argo-cd/values.yaml#L431-L456), [argo-rollouts](https://github.com/argoproj/argo-helm/blob/4dd31571b3ce2d90bd3598ca020e70cd887c6d23/charts/argo-rollouts/values.yaml#L30-L39) and [argo-workflows](https://github.com/argoproj/argo-helm/blob/4b8703db7571b4131262640be1e0fa3efbfcffb6/charts/argo-workflows/values.yaml#L561lL585).

**Comment by vladlosev** [comment]
I think it should be removed from those, as well.

**Comment by mkilchhofer** [comment]
@vladlosev This is for sure not a security issue. It really doesn't matter how can people are allowed to commit to a repo or do a `helm upgrade bla bla --reuse-values --values bla.yaml`. If a user can deploy via Helm, he/she can also deploy it via plain YAML or Kustomize.

I really appreciate this change and we should merge it. Every bitnami chart and a variety of other charts supports this. Use cases might be:
- Deploy a custom "Ingress" resource like Contours `HTTPRoute`, Istios `Gateway`
- Deploy secrets via external-secrets.io, or the examples in this PR (secrets-store CSI)
- Deploy custom NetworkPolicy objects with more complex rules like Ciliums `CiliumNetworkPolicy` or Calicos `NetworkPolicy`
- etc.

**Review by mkilchhofer — APPROVED** [review]
LGTM 💯

**Review by pdrastil — APPROVED** [review]

**Pull request merged**
