### PR TITLE
Add ssh-known-hosts and tls cert cms and vols

### LINKED ISSUE #111: Repo-server for Argo-CD 1.2 and newer is incomplete
The repo server now -has- to have volume mounts for the ssh known hosts and tls certs: https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L2832

The current charts do not include these mounts by default.

### PR DESCRIPTION
**Pull request by carsonoid**
Fixes #111

### CODE REVIEW

**Comment by alexec** [comment]
@jannfis @alexmt could you please review/approve?

**Comment by leoxiongideahq** [comment]
Hmm, just tested the PR and it does creates the `ConfigMap` and mounts the file into the pods, but Argo still can't seem to find the map. Am I doing something wrong?

```
 ~  kubectl get cm -n argo-cd                                            258ms  Fri Sep 20 11:28:02 2019
NAME                        DATA   AGE
argocd-cm                   1      21m
argocd-rbac-cm              0      21m
argocd-ssh-known-hosts-cm   1      15m
argocd-tls-certs-cm         0      15m
```

image

**Comment by leoxiongideahq** [comment]
Ahh, Argo expects the label on the `ConfigMap` to be [`app.kubernetes.io/part-of: argocd`](https://github.com/carsonoid/argo-helm/blob/repo-volumes/charts/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml#L18), however the TLS certs and SSH known hosts' label is [`app.kubernetes.io/part-of: argo-cd`](https://github.com/carsonoid/argo-helm/blob/repo-volumes/charts/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml#L18) by default.

Would just need to change the new `ConfigMaps` to the same as the other hard coded values.

**Comment by alexec** [comment]
New PR?

**Comment by leoxiongideahq** [comment]
Yeah, will flick one up now.

**Pull request merged**
