### PR TITLE
feat(argo-cd): Add ability to create network policies

### LINKED ISSUE #799: [argo-cd] Add NetworkPolicies
**Is your feature request related to a problem? Please describe.**
The upstream Kustomize manifests were extended with NetworkPolicy objects:
- https://github.com/argoproj/argo-cd/pull/6156/files
- https://github.com/argoproj/argo-cd/pull/6277/files

**Describe the solution you'd like**
Sync the manifests into the chart

**Describe alternatives you've considered**
Not implement these manifests

**Additional context**
See upstream PRs as listed in the first section.

### PR DESCRIPTION
**Pull request by mkilchhofer**
This resolves #799 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by toneill818 — APPROVED** [review]
lgtm

**Review by mbevc1 — APPROVED** [review]

**Comment by mkilchhofer** [comment]
Hi @mbevc1 could you please review and approve  again? :-) I needed to update the branch (and bump the version again)

**Review by mbevc1 — APPROVED** [review]

**Comment by mkilchhofer** [comment]
Hmm maybe you (@mbevc1 ) were not in the CODEOWNERS file when I opened this PR. Github wants a review from one of these 4 humans:
image

**Comment by mbevc1** [comment]
@mkilchhofer I think this is sorted now and my review should enable merging this one.

**Comment by salzig** [comment]
When deploying ArgoCD helm chart with `global.networkpolicy.create=true` and `server.ingress.enabled=true` we're missing a Policy to allow traffic from the ingress-controller.

**Pull request merged**
