### PR TITLE
fix(argo-cd): create service account for repo server by default

### PR DESCRIPTION
**Pull request by eddycharly**
This PR enables the creation of a service account for repo server by default.

### CODE REVIEW

**Comment by mbevc1** [comment]
Thanks, seems this would align this to other charts. Could you please provide changelog infor as well?

**Comment by eddycharly** [comment]
@mbevc1 sure, how shall I provide the changelog ?

**Comment by mbevc1** [comment]
There is an annotation that is used, i.e. https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/Chart.yaml#L22-L24

**Comment by mbevc1** [comment]
Thanks! Mind you need to replace current one as artifacthub is appending it automatically.

**Comment by eddycharly** [comment]
Done, do I need to bump the chart version ?
I guess i will have to regen the docs too.

**Comment by mbevc1** [comment]
Yes, please. Version needs bumping as well. Docs should be fine unless there are any changes related to those.

**Comment by eddycharly** [comment]
@mbevc1 version bumped and docs up to date.

**Review by mbevc1 — APPROVED** [review]

**Comment by mbevc1** [comment]
Looks good, just before merging thinking if we should bump minor version as this changes current default :thinking: 
Thoughts @mkilchhofer @davidkarlsen @yann-soubeyrand ?

**Review by mkilchhofer — COMMENTED** [review]
I wanted to ask for the use case? :-)

The upstream manifest (which are our template) do not create a ServiceAccount for the repo-server. Also the server does not have a mounted service account token by default

**Comment by eddycharly** [comment]
@mkilchhofer the use case is to identify to allow usage of `CiliumNetworkPolicy` with rules based on service accounts.

**Comment by eddycharly** [comment]
IMHO it shouldn't hurt to have a service account. Even if you don't specify one it will fallback to use `default`.
TBH, i don't see any case where it's not advisable to create one.

**Comment by mkilchhofer** [comment]
> @mkilchhofer the use case is to identify to allow usage of `CiliumNetworkPolicy` with rules based on service accounts.

Okay. This is a valable use case, I also override to true as I use helm plugins talking to the kube-api.

But it still is not comply in these two ideas:
- charts README
  > The default installation is intended to be similar to the provided ArgoCD [releases](https://github.com/argoproj/argo-cd/releases).
- least privilege principle (okay to be fair, the default SA normally also habe kube-api access)

Idk, I am okay if we proceed and merge as it is such a small change ;)

**Comment by eddycharly** [comment]
> Idk, I am okay if we proceed and merge as it is such a small change ;)

Let's do that ;)

**Pull request merged**
