### PR TITLE
feat(argo-rollouts): allows adding args to argo-rollout controller

### PR DESCRIPTION
**Pull request by aweis89**
- Adds args to values as are often required to customize the behaviour of the contoller

### CODE REVIEW

**Comment by cabrinha** [comment]
@aweis89 lets bump the chart version to 0.3.6

**Comment by cabrinha** [comment]
Thanks for the PR!

Try to make your build green. Seems like you need to bump your version.

**Comment by alexec** [comment]
@cabrinha you're approval is adequate for any PR.  @aweis89 please rebase.

**Review by yann-soubeyrand — CHANGES_REQUESTED** [review]
There is a problem whith this PR: without digging into the details, it removes way too much things, like the Argo CD chart for example ;-)

**Pull request closed without merging**
