### PR TITLE
fix(argo-workflows): use template for ingress .Capabilities

### LINKED ISSUE #794: argo-workflow: Ingress templating is misbehaving for <1.19 clusters
**Describe the bug**
Since https://github.com/argoproj/argo-helm/pull/747, the `Ingress` templating will not work properly on <1.19 K8s clusters (tested on 1.18.8). The ingress manifest is generated with `networking.k8s.io/v1` API but it's not available until 1.19 for `Ingress`. I'm not sure about older clusters than 1.18, the problem seems to be that when `networking.k8s.io/v1` is available on the cluster, either for `Ingress` or for anything else, the template will generate a `networking.k8s.io/v1` Ingress.

**To Reproduce**
1. Install the chart on a <1.19 cluster
2. The install will fail with a validation error

**Expected behavior**
The `Ingress` manifest should be generated for `networking.k8s.io/v1beta1` API.

### PR DESCRIPTION
**Pull request by Byh0ki**
This PR fixes #794.

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — COMMENTED** [review]
This will not fix the behaviour described in #794 but it consolidates multiple evaluations to a central point to implement a workaround for the real issue. Real issue is that when deploying this chart through a tool like ArgoCD (and I think also Pulumi), helm is only used for templating and not for the real deployment.

When only using "helm template", helm does not contact the API server by design. There are fixes in helm 3.6.0 and argo-cd PR https://github.com/argoproj/argo-cd/pull/6359. Please see duplicated issue: https://github.com/argoproj/argo-helm/issues/753

**Comment by mkilchhofer** [comment]
Would you mind to implement this here also?:
- https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L6
- https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/_helpers.tpl#L143-L161

**Comment by mkilchhofer** [comment]
> It's fixing the issue when using a simple `helm install`. I'm not currently using argo-cd to deploy this so I can't test it for this use case. That's why I missed #753, I thought that it was specific to argo-cd and not exactly the same use case, ence my issue 😅

Hmm, `helm install` did fail with the previous installation. Interesting! Maybe this `Capabilities.APIVersions.Has` does not work properly in helm v3.
Can you test if it still works with my addition? If so, I will approve and merge once you give green light from your side :-)

**Comment by Byh0ki** [comment]
Hello,

> Hmm, helm install did fail with the previous implementation? Interesting! Maybe this Capabilities.APIVersions.Has does not work properly in helm v3.

Yes, as stated in my original issue (#794), the issue comes from the fact that the APIVersion `networking.k8s.io/v1` is available on 1.18 cluster for the `NetworkPolicies` resource. So the test:
```
if .Capabilities.APIVersions.Has "networking.k8s.io/v1"
```
will always evaluate at `true` on a 1.18 cluster, even if the Ingress is only available as a `networking.k8s.io/v1beta` resource. That's why my original fix was enough for me, it uses the same template as here https://github.com/argoproj/argo-helm/blob/87af20fd06f87b8a05b14ad33738244067102d21/charts/argo-workflows/templates/server/server-ingress.yaml#L6 to get the correct APIVersion. The argo-cd chart is already using the same template. https://github.com/argoproj/argo-helm/blob/87af20fd06f87b8a05b14ad33738244067102d21/charts/argo-cd/templates/argocd-server/ingress.yaml#L22

> Can you test if it still works with my addition? If so, I will approve and merge once you give green light from your side :-)

Will test today and report back here :)

**Comment by Byh0ki** [comment]
`helm install` works as intended on 1.18 k8s cluster with the changes in this PR :)

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
