### PR TITLE
fix(argo-cd): add missing permissions to run actions

### PR DESCRIPTION
**Pull request by mcanevet**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by pdrastil** [comment]
@mcanevet Is this used for your custom UI action that you've supplied to configuration or is this supported out of the box? I don't see any permission changes in upstream ClusterRole for Argo CD server - https://github.com/argoproj/argo-cd/blob/v2.8.0/manifests/cluster-rbac/server/argocd-server-clusterrole.yaml

If the new functionality allows users to define actions on various resources (not just jobs or workflows) that require extra permissions, we should make RBAC configurable for additional use cases.

**Comment by mcanevet** [comment]
@pdrastil this is related to this PR https://github.com/argoproj/argo-cd/pull/12925. Without this permissions, the actions do not work.

**Comment by mcanevet** [comment]
You can easily test it if you have a `Cronjob` managed by ArgoCD. There is a new "Create Job" action available, which triggers `kubectl create job --from=<the cronjob>`.

**Review by pdrastil — APPROVED** [review]
LGTM

**Review by mbevc1 — APPROVED** [review]

**Pull request merged**
