### PR TITLE
feat(argo-cd): Extract ServiceMonitor interval to values

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
## Problem

My production environment is using 60s scrape interval:
- Some charts has no defaults(so used default value in prometheus and it is just works)
- Some charts has 30s defaults in values files
- This chart has hardcoded values in manifests, so no chance to use 60s interval

## Decisions

It is better to have no defaults at all, ServiceMonitor will be fallback to scrapeInterval from defined prometheus configuration, so one place to change scrape intervals and only one reason to add it manually - to override defaults if it really need

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

## Templated version

```
helm template test-release -n test-namespace -f .\values.yaml  . > templated.yaml
```

```yaml
# Source: argo-cd/templates/argocd-application-controller/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-release-argocd-application-controller
  labels:
    helm.sh/chart: argo-cd-3.3.5
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/instance: test-release
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - test-namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/instance: test-release
      app.kubernetes.io/component: application-controller
---
# Source: argo-cd/templates/argocd-repo-server/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-release-argocd-repo-server
  labels:
    helm.sh/chart: argo-cd-3.3.5
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: test-release
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - test-namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server-metrics
      app.kubernetes.io/instance: test-release
      app.kubernetes.io/component: repo-server
---
# Source: argo-cd/templates/argocd-server/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-release-argocd-server
  labels:
    helm.sh/chart: argo-cd-3.3.5
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: test-release
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - test-namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
      app.kubernetes.io/instance: test-release
      app.kubernetes.io/component: server
---
# Source: argo-cd/templates/dex/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-release-argocd-dex-server
  labels:
    helm.sh/chart: argo-cd-3.3.5
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/instance: test-release
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - test-namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/instance: test-release
      app.kubernetes.io/component: dex-server
```

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Hi @sergeyshaykhullin 
Thank you for this contribution. Regarding the interval, this is perfectly fine. But I am not sure, if it makes sense to also extract the path. What's your use case?

**Comment by sergeyshaykhullin** [comment]
@mkilchhofer No, just intuitive move, i think i don't need to override path, thanks!

**Comment by mkilchhofer** [comment]
> @mkilchhofer No, just intuitive move, i think i don't need to override path, thanks!

👍
Can you reword your last commit to contain the `Signed-off-by: Sergey Shaykhullin <sergeyshaykhullin@gmail.com>`? Then I will approve this PR and merge it.

**Comment by sergeyshaykhullin** [comment]
@mkilchhofer Done)

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
