### PR TITLE
feat(argo-cd): Upgrade argocd to 2.11.0 + crd changes

### PR DESCRIPTION
**Pull request by DrFaust92**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by tico24** [comment]
There's other changes beyond just CRDs I'm afraid. I'm on mobile but I see appset controller rbac changes and some new env vars on various deployments.

**Comment by DrFaust92** [comment]
[tico24](https://github.com/tico24) thanks! checking and adding missing rbac

**Comment by DrFaust92** [comment]
@tico24 i did not see any missing rbac. but i did find one missing env var which i have added as well

**Comment by pdrastil** [comment]
@DrFaust92 Hi thanks for the sync - I've checked with upstream and looks good.

**Review by pdrastil — APPROVED** [review]

**Review by mbevc1 — APPROVED** [review]

**Review by yu-croco — APPROVED** [review]

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
