### PR TITLE
chore(argo-cd): create roles instead of rolebindings when singleNamespace is true

### PR DESCRIPTION
**Pull request by searsaw**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by searsaw** [comment]
This is failing for a similar reason I had issues testing my changes. A `403` is being returned from the Kubernetes charts repo.

**Comment by searsaw** [comment]
I've updated the stable Helm repos to point to their new location at `https://charts.helm.sh/stable`. However, the linting is still failing. This may be due to CircleCI being configured to bring in the chart repo `argo=https://argoproj.github.io/argo-helm`, which might be pulling in the existing one that still has a dependency on the old stable location. I'm not super familiar with CircleCI, however. So this may be incorrect.

**Comment by stefansedich** [comment]
@searsaw CI should be fixed with the merge of #541 do you want to rebase and we can get this one in.

**Comment by searsaw** [comment]
@stefansedich can we get this merged soon?

**Review by seanson — APPROVED** [review]

**Pull request merged**
