### PR TITLE
Updating argocd-metrics service to target application-controller

### LINKED ISSUE #51: Service argocd-metrics targetting wrong pods
Service `argocd-metrics` has a labelSelector for `argocd-server` not `argocd-application-controller`.

When looking at the [argocd-metrics manifest](https://github.com/argoproj/argo-cd/blob/master/manifests/base/application-controller/argocd-metrics.yaml) for argo-cd you can see it selects pods with label selector `app.kubernetes.io/name: argocd-application-controller`.

In the [argo-cd helm chart](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-metrics-service.yaml) it has a label selector effectively `app.kubernetes.io/name: argocd-server`.

`argocd-application-controller` is exposing the metrics.

### PR DESCRIPTION
**Pull request by arnarg**
Fixes #51

### CODE REVIEW

**Comment by alexec** [comment]
Hi, can you please resolve the conflicts?

**Comment by alexec** [comment]
I'm not clear on how to test this change. Any chance you can give me some suggestions please?

**Comment by arnarg** [comment]
You could `curl http://argocd-metrics:8082/metrics` from another pod.

But really I'm just aligning the helm chart to the [manifest in the argo-cd repo](https://github.com/argoproj/argo-cd/blob/master/manifests/base/application-controller/argocd-metrics.yaml).

**Comment by arnarg** [comment]
What more information is needed?

**Comment by alexec** [comment]
I'd like to manually test this change. I was wondering if you could give me pointers on how you think I should do that please?

**Comment by arnarg** [comment]
Basically this just creates a service for application controller where it exposes Prometheus metrics.

You could simply `curl http://argocd-metrics:8082/metrics` (assuming no overrides in values.yaml) from another pod and see if it returns Prometheus metrics and I would assume that covers everything needed to test this.

If you want to go all in and see if metrics show up in Prometheus you'll need to deploy [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) along with the first `ServiceMonitor` in [metrics.md doc](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/metrics.md). `ServiceMonitor` targets services that have pods that expose Prometheus metrics.

**Comment by alexec** [comment]
@arnarg are you good to test this on the master if I merge?

**Comment by arnarg** [comment]
It's working as expected on master.

**Pull request merged**
