### PR TITLE
feat: add kubernetes version tag and set container security capabilities

### PR DESCRIPTION
**Pull request by bartse**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by spencergilbert** [comment]
@seanson was there a reason the chart didn't have this label before? it does look fairly common in stable charts.

**Comment by seanson** [comment]
> @seanson was there a reason the chart didn't have this label before? it does look fairly common in stable charts.

No reason but there's no real checklist for things to include / best practices so we just add things ad-hoc.

**Comment by yann-soubeyrand** [comment]
Hi,
@bartse can you fix this PR, please? The chart cannot be installed any more since by default tags are empty ;-)

**Comment by yann-soubeyrand** [comment]
Also, you introduced a lot of trailing spaces.

**Comment by bartse** [comment]
Somehow I missed those default values. There is an open PR for this to fix it 208
Not sure how I missed the default values since Im using the forked version locally.

**Pull request merged**
