### PR TITLE
fix(argo-events): spec.versions.schema Required for argo-events crds

### PR DESCRIPTION
**Pull request by kostas-theo**
This is to fix the issue which I raised here: https://github.com/argoproj/argo-helm/issues/599

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by georgekaz** [comment]
Hi @kostas-theo , I've just come across this problem too, and although your patch allows the CRDs to install, it doesn't allow the actual objects to install e.g. "error validating data: ValidationError(Sensor): unknown field "spec" in io.argoproj.v1alpha1.Sensor". It seems like a working spec can be taken from here: https://github.com/argoproj/argo-events/blob/master/manifests/install.yaml#L1-L119

**Comment by kostas-theo** [comment]
@georgekaz - thanks for the pointer - updated

**Comment by kostas-theo** [comment]
@vladlosev , @alexec - could we perhaps get this small change labelled as a bugfix and reviewed?

**Comment by vladlosev** [comment]
My personal preference is to update the CRDs in the `templates` directory to be consistent with these definitions. But you will also need an approval from one of code owners.

**Comment by vladlosev** [comment]
LGTM now

**Comment by kostas-theo** [comment]
@jbehling , @VaibhavPage - could I please get a review here?

**Review by oliverbaehler — APPROVED** [review]
lgtm

**Comment by alexec** [comment]
I'm taking a bit of time to merge older approved PRs.

**Pull request merged**
