### PR TITLE
fix(argo-cd): Fix REDIS_PASSWORD optional flag

### PR DESCRIPTION
**Pull request by bhavinkotak**
Should fix this [Issue](https://github.com/argoproj/argo-helm/issues/3057)

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Review by tico24 — APPROVED** [review]

**Comment by tico24** [comment]
You'll need to argue with DCO to get it to merge but overall approved by me.

**Comment by bhavinkotak** [comment]
DCO is fixed now.. sorry for the earlier miss..

**Review by mbevc1 — APPROVED** [review]

**Review by yu-croco — APPROVED** [review]

**Comment by mkilchhofer** [comment]
@yu-croco @mbevc1 we already were there. Sorry for not being more active on this PR. Now an other use case is broken ;) 

- https://github.com/argoproj/argo-helm/pull/2839

**Comment by mbevc1** [comment]
Ah, forgot about that one :sweat_smile:

**Comment by yu-croco** [comment]
ahhhhh 🫠

**Pull request merged**
