### PR TITLE
feat(argo-rollouts): Match autogenerated/tested CRDs in upstream argo-rollouts

### PR DESCRIPTION
**Pull request by anderson4u2**
Matches the [MR raised in upstream argo-rollouts](https://github.com/argoproj/argo-rollouts/pull/1044)

Using fields of arrays that are called items [fails validation in k8s 1.16](https://github.com/kubernetes/kubernetes/issues/84880) and lower. Tested on [1.17+ and it's fine](https://github.com/kubernetes/kubernetes/pull/85223)

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by cabrinha** [comment]
please fix the semantic error you see here in the CI

**Comment by anderson4u2** [comment]
> please fix the semantic error you see here in the CI

Hello, thanks for looking, sorry missed this. Should be all fixed now :). 

Would it be desirable to have an MR to add a test that these CRDs are not diverging from argo-rollouts upstream? only CRDs. This would force making changes in argo-rollouts first, and then bring those changes here.

**Comment by cabrinha** [comment]
> > please fix the semantic error you see here in the CI
> 
> Hello, thanks for looking, sorry missed this. Should be all fixed now :).
> 
> Would it be desirable to have an MR to add a test that these CRDs are not diverging from argo-rollouts upstream? only CRDs. This would force making changes in argo-rollouts first, and then bring those changes here.

Sounds interesting.

**Review by cabrinha — APPROVED** [review]

**Comment by anderson4u2** [comment]
Hi @cabrinha, I've pushed a commit to update the CRDs to match the upstream, which changed recently. I've also added a field for adding annotations to CRDs. Let me know if this is still ok to merge and I'll do after merging the upstream. Thanks!

**Comment by anderson4u2** [comment]
Hi, FYI this is good to merge

**Review by cabrinha — APPROVED** [review]

**Pull request merged**
