### PR TITLE
fix(argo-events): missing argument for toYaml function in deployment template

### PR DESCRIPTION
**Pull request by shaw8ii**
Signed-off-by: shawqi.alazzawi@optimumpartners.co

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @shaw8ii , thank you for your PR.
Will you please update (remove old one and add new one) changelogs on [argo-events/Chart.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/Chart.yaml#L17-L19) , like below ?

```diff
annotations:
  artifacthub.io/changes: |
-    - kind: added
-      description: Add install guide on README
+    - kind: fixed
+      description: xxxxxxxxxxxx
```

ref: https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog

**Comment by yu-croco** [comment]
Hi @shaw8ii , will you please fix failed CI and resolve conflict? 🙋 
Once CI passes, I will approve it.

**Comment by yu-croco** [comment]
I think that once you bump version on [Chart.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/Chart.yaml#L5), CI will pass.
ref: https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning

image

**Review by yu-croco — APPROVED** [review]
Thank you for your contribution! LGTM

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
