### PR TITLE
fix(argo-rollouts): Add subscriptions into notifcations-configmap

### PR DESCRIPTION
**Pull request by jaimeph**
Resolves https://github.com/argoproj/argo-helm/issues/2792 
Add subscriptions into notification-configmap.
https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/subscriptions/#default-subscriptions

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @jaimeph , thank you for your PR.
Since it's Argo Rollouts and there is no doc ref about it in your PR, can you please give us any ref(code or docs) about this?

**Comment by jaimeph** [comment]
There is no documentation on this in argo-rollouts. But as argo-rollouts and argo-cd share the same component/version of https://github.com/argoproj/notifications-engine I understood that the behavior should be the same, I did a test in my environment and it is functional.

**Review by yu-croco — APPROVED** [review]

**Comment by ajax-bychenok-y** [comment]
> I understood that the behavior should be the same

Would be nice to have at least тщеу regarding global subscription in doc of Argo Rollouts. For now there is nothing https://argo-rollouts.readthedocs.io/en/stable/features/notifications/#subscriptions

But for ArgoCD https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions
https://argo-cd.readthedocs.io/en/stable/user-guide/subscriptions/#default-subscriptions

**Review by mbevc1 — APPROVED** [review]

**Comment by ajax-bychenok-y** [comment]
Thank you, guys.

**Pull request merged**
