### PR TITLE
Allow disabling ui and deploying ui related resources

### PR DESCRIPTION
**Pull request by kbial**
Allow disabling the UI and deploying UI related resources.

For security reasons we do not want to allow the UI in production deployments and disabling ingress is not enough since it’s preferable to not have unused resources running.

### CODE REVIEW

**Comment by bclermont** [comment]
as long as you don't turn on ingress, it don't really make a big difference, no?

**Comment by wookasz** [comment]
> as long as you don't turn on ingress, it don't really make a big difference, no?

That's not true. There's an unnecessary container sitting around in the cluster, which violates security best practices and uses up some, albeit small, amount of resources unnecessarily. Our vulnerability scanning tools are flagging the image as well so the choice is to either continually patch and maintain something that isn't used or just get rid of it.

**Comment by bclermont** [comment]
You're right.

BTW, which "vulnerability scanning tools" you are using?

**Comment by wookasz** [comment]
We're using twistlock.

**Comment by alexec** [comment]
@kbial this looks good to me, but can you fix the merge conflict please?

**Pull request merged**
