### PR TITLE
fix(argo-cd): Use ingress crt for dex when enabled

### PR DESCRIPTION
**Pull request by ShimiTaNaka**
Fixes: https://github.com/argoproj/argo-helm/issues/2171

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by tico24** [comment]
It's failing at exactly the point you've changed, so I'd argue it's related to your change :)

templates/argocd-server/deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 336: mapping values are not allowed in this context

**Comment by ShimiTaNaka** [comment]
ok, so it's line 336 after rendering, because the chart itself change is in line 426 :)
Checking

**Comment by mkilchhofer** [comment]
I am not sure if this is needed. Dex is controlled by a binary which is copied into the dex container. I thought that this utility does generate some TLS config between argo-cd-server and dex. And dex is exposed via a reverse proxy component inside argo-cd-server

**Comment by ShimiTaNaka** [comment]
It actually is
specifically when setting up OKTA.
The change doesn't require anything on the dex itself actually and dex isn't even configured with SSL https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L994C12-L994C12
Instead, we configure ingress for argocd-server.
During the login, argocd-server makes an API endpoint to:
https://ui.argocd.yourorganization.net/api/dex/.well-known/openid-configuration
and then there is an SSL issue.
I can't reproduce it on a working environment, seems that the CA is cached, but it's shown in the server logs:
`Initializing OIDC provider (issuer: https://ui.argocd.yourorganization.net/api/dex)"`
(obviously with our private URL) and there was an SSL error, it was fixed once we changed the secret name in question

**Comment by ShimiTaNaka** [comment]
Important to mention, this does not create a certificate for DEX, rather, if we create an ingress to ArgoCD *server*, with a certificate, map it.

**Comment by ShimiTaNaka** [comment]
I think I've found a better solution
I'll check it out first

**Comment by ShimiTaNaka** [comment]
Current implementation inspired by https://github.com/argoproj/argo-cd/issues/7572#issuecomment-1057376181

I also hope it makes the incentive clearer :)

**Comment by mkilchhofer** [comment]
I can still not follow your issue.
For ingress traffic from outside kubernetes to dex (user callbacks), the path chain is:

Ingress -> argocd-server (acts as a proxy) -> dex

For outgoing traffic from dex to the upstream IdP, traffic flows directly:

Dex -> IdP

**Comment by ShimiTaNaka** [comment]
I have tested it
and I know it can be achieved by it, it's just makes things simpler.
The login flow is as follows:

1. User goes to https://argocd.domain.suffix and clicks "Sign in with Okta"
2. Argo-server sends him to ssoUrl (As specified in https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/okta/)
3. User logs in, and gets a redirect to https://argocd.domain.suffix/api/dex/callback
4. User gets authenticated with a session (for https://argocd.domain.suffix site) and gets 303 redirect to https://argocd.domain.suffix
5. argo-server makes API call to https://argocd.domain.suffix/api/dex/.well-known/openid-configuration to validate the session cookie signature

The last part fails because argo-server communicates with the dex via external call all the way with the ingress and not internally, so when the ingress is using self signed CA, the call fails.

As you've mentioned, this can be also achieved by passing the values you've provided, the PR as it is just makes it easier on the user

I will try to reproduce and get back to you on it

**Pull request closed without merging**
