### PR TITLE
fix(argo-cd): Avoid invalid labels when image tags have digest

### PR DESCRIPTION
**Pull request by sathieu**
This was missing from https://github.com/argoproj/argo-helm/pull/1368
to fix https://github.com/argoproj/argo-helm/issues/417.

Fix the following validation error:

> Error: failed to create resource: Deployment.apps "argocd-applicationset-controller" is invalid: [metadata.labels: Invalid value: "v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572": a valid label must be an empty string or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'',  or ''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?''), spec.template.labels: Invalid value: "v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572": a valid label must be an empty string or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'',  or ''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'')]

Ref: https://gitlab.com/kubitus-project/kubitus-installer/-/jobs/2922927151#L1878

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by sathieu** [comment]
Tested with:

```
$ helm template . --set global.image.tag=v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c5725fe4052681950dc --set dex.image.tag=v2.33.0@sha256:62902bd3a7ce4a73ed44e28884bffec04bcaa4a07e31e043173bdce289717e80 --set redis.image.tag=7.0.4-alpine@sha256:7c9e7c305125c68354c4902ed09a3c6da96436a5a2929b73f29748d56cf8e3c3| grep -F app.kubernetes.io/version
    app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
        app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
    app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
        app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
    app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
        app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
    app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
        app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
    app.kubernetes.io/version: "v2-33-0-sha256-62902bd3a7ce4a73ed44e28884bffec04bcaa4a07e31e043"
        app.kubernetes.io/version: "v2-33-0-sha256-62902bd3a7ce4a73ed44e28884bffec04bcaa4a07e31e043"
    app.kubernetes.io/version: "7-0-4-alpine-sha256-7c9e7c305125c68354c4902ed09a3c6da96436a5a29"
        app.kubernetes.io/version: "7-0-4-alpine-sha256-7c9e7c305125c68354c4902ed09a3c6da96436a5a29"
    app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
        app.kubernetes.io/version: "v2-4-4-sha256-9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c572"
```

**Comment by mkilchhofer** [comment]
What about dropping the version label completely @mbevc1, @jmeridth, @pdrastil?

Upstream manifests does not define the version label:
[v2.4.11/](https://github.com/argoproj/argo-cd/blob/v2.4.11/manifests/install.yaml)

**Comment by yu-croco** [comment]
Aligning to upstream's way sounds good to me. 🙋

**Comment by sathieu** [comment]
I've created another PR: #1432

**Comment by mbevc1** [comment]
Yup, let's try to keep it aligned with the upstream :+1:

**Comment by mkilchhofer** [comment]
Solved via https://github.com/argoproj/argo-helm/pull/1432

**Pull request closed without merging**
