### PR TITLE
fix(argo-cd): Fix (full)nameOverride redis-ha sub-chart

### LINKED ISSUE #722: Redis-ha name (full)nameOverride breaks the ArgoCD helm chart
https://github.com/argoproj/argo-helm/blob/e39ccfe31585a9843ac64cbdc0706e098e992df4/charts/argo-cd/templates/_helpers.tpl#L48

It seems that the helm chart does not keep into account that redis name can be overridden.

How to rerproduce:

1.  Do a helm install with name test-arg

2. Override the values:
`
argocd:
  fullnameOverride: "argocd"
  redis-ha:
    fullnameOverride: "argocd-redis-ha"
    enabled: true
`
 This results in a bug upon using Argocd:
`failed to verify app state CjOtTpvHfN: dial tcp: lookup npr-argocd-redis-ha-haproxy on 10.128.0.35:53: no such host`

A simple fix would just be to check if fullnameOverride or nameOverride have been set.

### PR DESCRIPTION
**Pull request by TPX01**
Fixes #722

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by oliverbaehler** [comment]
Is this art or can we close this?

**Comment by TPX01** [comment]
@oliverbaehler i'm a bit new in the commit policies (or) for this. It seems my last push went to shit 😅..

**Comment by mkilchhofer** [comment]
Which commit do you mean? this one here: https://github.com/TPX01/argo-helm/commit/071e5d601eaa64f2a0af82657d1b84381e393a85?

**Comment by TPX01** [comment]
> Which commit do you mean? this one here: [TPX01@071e5d6](https://github.com/TPX01/argo-helm/commit/071e5d601eaa64f2a0af82657d1b84381e393a85)?

That's correct

**Comment by mkilchhofer** [comment]
What about fixing it like this:
```diff
$ git diff
diff --git a/charts/argo-cd/templates/_helpers.tpl b/charts/argo-cd/templates/_helpers.tpl
index 79723e7..820db95 100644
--- a/charts/argo-cd/templates/_helpers.tpl
+++ b/charts/argo-cd/templates/_helpers.tpl
@@ -42,10 +42,11 @@ Create dex name and version as used by the chart label.
 Create redis name and version as used by the chart label.
 */}}
 {{- define "argo-cd.redis.fullname" -}}
-{{ $redisHa := (index .Values "redis-ha") }}
+{{- $redisHa := (index .Values "redis-ha") -}}
+{{- $redisHaContext := dict "Chart" (dict "Name" "redis-ha") "Release" .Release "Values" $redisHa -}}
 {{- if $redisHa.enabled -}}
     {{- if $redisHa.haproxy.enabled -}}
-        {{- printf "%s-redis-ha-haproxy" .Release.Name | trunc 63 | trimSuffix "-" -}}
+        {{- printf "%s-haproxy" (include "redis-ha.fullname" $redisHaContext) | trunc 63 | trimSuffix "-" -}}
     {{- end -}}
 {{- else -}}
 {{- printf "%s-%s" (include "argo-cd.fullname" .) .Values.redis.name | trunc 63 | trimSuffix "-" -}
```

**Comment by TPX01** [comment]
> What about fixing it like this:
> 
> ```diff
> $ git diff
> diff --git a/charts/argo-cd/templates/_helpers.tpl b/charts/argo-cd/templates/_helpers.tpl
> index 79723e7..820db95 100644
> --- a/charts/argo-cd/templates/_helpers.tpl
> +++ b/charts/argo-cd/templates/_helpers.tpl
> @@ -42,10 +42,11 @@ Create dex name and version as used by the chart label.
>  Create redis name and version as used by the chart label.
>  */}}
>  {{- define "argo-cd.redis.fullname" -}}
> -{{ $redisHa := (index .Values "redis-ha") }}
> +{{- $redisHa := (index .Values "redis-ha") -}}
> +{{- $redisHaContext := dict "Chart" (dict "Name" "redis-ha") "Release" .Release "Values" $redisHa -}}
>  {{- if $redisHa.enabled -}}
>      {{- if $redisHa.haproxy.enabled -}}
> -        {{- printf "%s-redis-ha-haproxy" .Release.Name | trunc 63 | trimSuffix "-" -}}
> +        {{- printf "%s-haproxy" (include "redis-ha.fullname" $redisHaContext) | trunc 63 | trimSuffix "-" -}}
>      {{- end -}}
>  {{- else -}}
>  {{- printf "%s-%s" (include "argo-cd.fullname" .) .Values.redis.name | trunc 63 | trimSuffix "-" -}
> ```

Will test it tonight but looks cleaner indeed

**Comment by mkilchhofer** [comment]
@TPX01 I updated your branch, can you test it? :-)

**Review by mbevc1 — APPROVED** [review]
LGTM

**Comment by TPX01** [comment]
> @TPX01 I updated your branch, can you test it? :-)

Works like a charm! 😊

**Comment by TPX01** [comment]
@mkilchhofer thanks for helping out on this one!

**Pull request merged**
