### PR TITLE
feat(argo-cd): Add ability to scrape redis metrics

### LINKED ISSUE #891: [argo-cd] Ability to scrape redis metrics
### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

Redis is the last component of ArgoCD which does not provide Prometheus metrics. It would be nice, if we could also deploy Prometheus metrics, ServiceMonitors and Network Policies.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mkilchhofer**
Resolves #891 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
FYI @pdrastil this PR now also include your relabeling stuff :-) thanks for pointing me to your PR.

**Comment by mkilchhofer** [comment]
Maybe something for you @mbevc1 ? ;)

**Comment by mbevc1** [comment]
Sure, if no one beats me to it I can have a look tomorrow :+1:

**Review by mbevc1 — APPROVED** [review]
LGTM, we just need to bump the version again before merging :wink:

**Review by mbevc1 — APPROVED** [review]

**Comment by mkilchhofer** [comment]
Oh, thx for the approve. I already rebased it simultaneously :-)

**Pull request merged**
