### PR TITLE
docs: Fixed typo in values comment

### PR DESCRIPTION
**Pull request by MichielDeMey**
Speficy -> Specify

Checklist:

* [ ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed the CLA and the build is green.
* [ ] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by stefansedich — APPROVED** [review]
LGTM

**Comment by stefansedich** [comment]
@MichielDeMey could you please bump the chart version.

**Comment by MichielDeMey** [comment]
Is that really needed for a typo or just to get past the checks? 🙂

**Comment by stefansedich** [comment]
> Is that really needed for a typo or just to get past the checks?

Will be needed to get past the CI checks so I can merge it :smile:

**Comment by MichielDeMey** [comment]
@stefansedich Sorry for the delay, the chart version is bumped. 😉

**Review by stefansedich — APPROVED** [review]

**Comment by stefansedich** [comment]
> @stefansedich Sorry for the delay, the chart version is bumped.

No problems, merged!

**Pull request merged**
