### PR TITLE
chore(CODEOWNERS): Nominate jmeridth as an approver

### PR DESCRIPTION
**Pull request by jmeridth**
Nominate jmeridth as an approver

Signed-off-by: jmeridth <jmeridth@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:
* [x] I have signed off all my commits as required by [DCO]

Not applicable:
* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
(https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
xref: #612

Yes, one more approver/maintainer for this repo. @alexec can you send an invitation?

**Comment by jmeridth** [comment]
@alexec any concerns on this request?

**Comment by alexec** [comment]
I think this needs to be approved by the other owners.

**Comment by jmeridth** [comment]
@alexec thank you

@stefansedich @vladlosev @yann-soubeyrand any concerns? Thank you all for your time and consideration.

**Comment by jmeridth** [comment]
Bump @stefansedich @vladlosev @yann-soubeyrand.  I'm here to help.  Again, thank you for your consideration.

**Comment by jmeridth** [comment]
I volunteer as tribute

😄

**Review by mbevc1 — APPROVED** [review]

**Comment by mbevc1** [comment]
I believe you'll need write permissions as well

**Comment by mbevc1** [comment]
Someone from the upstream project, probably @alexec could do that :thinking:

**Comment by jmeridth** [comment]
Thank you @alexec

**Pull request merged**
