### PR TITLE
feat(argo-cd): Add `existingVolumes` setting for remaining deployments with emptyDir volumes

### PR DESCRIPTION
**Pull request by bodgit**
#2410 added the `existingVolumes` setting for the repo-server component. This PR adds an equivalent setting to the other Argo CD components that have `emptyDir` volumes in their deployment so you can either use a PVC or further tune the `emptyDir` volume with `sizeLimit` parameters, etc. (which is what I do).

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
FYI
Regarding the failed CI, https://github.com/argoproj/argo-helm/issues/2460 is related. There is a PR for fixing in upstream, let's wait for it.

**Comment by yu-croco** [comment]
FYI: The CI is fixed now. 👍

**Comment by bodgit** [comment]
@yu-croco Rebased and all tests now pass.

**Review by yu-croco — APPROVED** [review]
LGTM

**Comment by mbevc1** [comment]
Probably needs rebasing rather than closing? :thinking:

**Comment by yu-croco** [comment]
Hi @bodgit , can you please fetch latest remote diff and resolve conflicts?

**Comment by mkilchhofer** [comment]
not stale

**Pull request closed without merging**
