### PR TITLE
chore!: Deprecate argocd-applicationset and argocd-notifications

### LINKED ISSUE #1219: deprecate applicationset and notification chart
### Is your feature request related to a problem?

Since these charts have merged into the main argocd chart, we should mark application set and notification helm chart as deprecated and write a notice in the readme that they should use the argocd main chart. 

### Related helm chart

argo-cd, argocd-applicationset, argocd-notifications

### Describe the solution you'd like

https://helm.sh/docs/topics/charts/#the-chartyaml-file
chart.yaml
```yaml
deprecated: true
```

Add readme notice
> ⚠️This controller has been merged into the main project since argocd [release 2.3.0](https://github.com/argoproj/argo-cd/releases/tag/v2.3.0). The deployment have moved to the [main argocd chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd), this chart is no longer maintained.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mkilchhofer**
Resolves #1219

/cc: Initial chart contributor @maruina (https://github.com/argoproj/argo-helm/pull/577), @andyfeller (https://github.com/argoproj/argo-helm/pull/365)

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
/cc: @pburgisser as of contribution https://github.com/argoproj/argo-helm/pull/1223

**Comment by davidkarlsen** [comment]
@mkilchhofer Can you bump the chart versions too please?

**Comment by mkilchhofer** [comment]
> @mkilchhofer Can you bump the chart versions too please?

Oh yes for sure. Done :)

**Review by davidkarlsen — APPROVED** [review]
lgtm

**Comment by andyfeller** [comment]
👍 nice work @mkilchhofer

**Pull request merged**
