### PR TITLE
Updates for Argo v2.5

### PR DESCRIPTION
**Pull request by sudermanjr**
This PR will update to v2.5.2. It implements the argo-server in addition to the UI in order to enable phasing out of the UI.

In addition, there are some changes in order to make the chart pass a `helm lint --strict`.  This was necessary to help me find a lot of the cruft that existed before and that I was adding as I did the update.

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by alexec** [comment]
Just FYI - v2.6.0 with GA on Friday.

**Comment by sudermanjr** [comment]
> Just FYI - v2.6.0 with GA on Friday.

Thanks for the heads up. I think it will be best to go ahead and merge this, and then make a new one to update to 2.6. That way those who want to try 2.5 first (and make sure it's stable) can do so

**Comment by paguos** [comment]
@sudermanjr can you also check my PR: https://github.com/argoproj/argo-helm/pull/258 and see if I missed something?

**Comment by sudermanjr** [comment]
> @sudermanjr can you also check my PR: #258 and see if I missed something?
> 
> I didn't notice that you opened a similar one ...

@paguos There is a fundamental conflict between your PR and mine. I don't particularly care which one goes in (that's up to the maintainers), but in yours you replace the UI with the server, and in mine I add the server as an additional "component" so that the UI can be deprecated later.

I'm pretty ambivalent to which approach is better. I think a maintainer (maybe @benjaminws ) needs to weigh in here.

**Comment by paguos** [comment]
@sudermanjr agree 👍

**Pull request closed without merging**
