### PR TITLE
feat(argo-cd): Allow chart to be deployed and only ship CRDs

### PR DESCRIPTION
**Pull request by cypher7682**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by cypher7682** [comment]
When deploying a separate cluster that is going to be managed by a remote argo, CRDs are needed for it to ship anything. This PR allows CRDs to be published without anything else in the chart coming with it.

**Comment by mkilchhofer** [comment]
I don't like this idea to be honest (too noisy on all resources and never seen this approach in the "wild"). If this is something we need to support I would be on the side to outsource the CRDs to a subchart.

What is the issue in pulling in the CRDs from the upstream repo as a Kustomize base like its described in the README.md?

**Comment by cypher7682** [comment]
> When I saw this PR, my first thoughts were:

I had the same thoughts doing this PR... don't worry. It's clunky AF; I am under no illusions 😂  If new charts are made, they'll need to make sure they have the `{{ if }}` otherwise CRD installations will randomly install miscellaneous apps.

A sub chart is definitely a better idea. I don't think the versioning matters all that much, helm wise. So far the versioning doesn't exist, so even starting at 0.0.1 would work. Existing deployments can just reference the sub-chart on 0.0.1. However...

Regarding the double PRs, I don't see a way to avoid that, to be honest; at least not without essentially guessing the version before it's shipped. On the other hand, copy pasting everything into a "slimmed down" chart is also not ideal.

I, too, would be interested in hearing from the maintainers on what their thoughts are on the best way forward.

**Comment by jmeridth** [comment]
As @mkilchhofer has stated, your use case is valid but maintaining it would currently be painful. I'm thinking on proposals here and other ideas.

**Comment by cypher7682** [comment]
Do you want me to move this to an issue, rather than a PR?

**Comment by jmeridth** [comment]
@cypher7682 As @mkilchhofer stated

> With my reflection about complexity this proposal here might look a bit clunky, but it is a KISS solution :D .

I'm good with this but can we do a PR per chart please?  Can you also sign your commits (`git commit -s`)?

**Comment by jmeridth** [comment]
@cypher7682 please wait before you break out the PRs.  We, the maintainers, are discussing options.  Will let you know asap.

**Pull request closed without merging**
