### PR TITLE
feat(argo-cd): add the ability to specify automountServiceAccountToken for argo-cd

### PR DESCRIPTION
**Pull request by joshuastern**
Checklist:

* [X] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [X] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
What is the motivation for this change?

**Comment by joshuastern** [comment]
> What is the motivation for this change?

As part of following best practices, we want to be able to explicitly configure this field rather than get it for free. When the `automountServiceAccountToken` is not set, a service account token is still mounted.

**Comment by davidkarlsen** [comment]
> > What is the motivation for this change?
> 
> As part of following best practices, we want to be able to explicitly configure this field rather than get it for free. When the `automountServiceAccountToken` is not set, a service account token is still mounted.

sgtm. can you get the semantic pr check to pass so we can merge it?

**Comment by joshuastern** [comment]
> > > What is the motivation for this change?
> > 
> > 
> > As part of following best practices, we want to be able to explicitly configure this field rather than get it for free. When the `automountServiceAccountToken` is not set, a service account token is still mounted.
> 
> sgtm. can you get the semantic pr check to pass so we can merge it?

done

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
