### PR TITLE
chore(argo-cd): Upgrade Argo Image to the latest version 2.5.1

### PR DESCRIPTION
**Pull request by wd**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by wd** [comment]
Version v2.5.1 includes an important security fix. https://github.com/argoproj/argo-cd/releases

**Comment by yu-croco** [comment]
Hi @wd , thank you for your contribution!

Could you please update change log below, though CI passed.? 🙋 
code: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml#L25
ref: https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog

**Comment by wd** [comment]
updated. I misunderstand that section in the Chart.yaml. I thought it was a normal annotation.

**Review by yu-croco — APPROVED** [review]
Thank you so much!

**Pull request merged**
