### PR TITLE
feat(argo): Add linux node selectors by default

### PR DESCRIPTION
**Pull request by lippertmarkus**
Starting with v2.9 Argo supports Windows Containers and can therefore be run in hybrid Kubernetes clusters consisting of Linux and Windows nodes (see https://github.com/argoproj/argo/pull/2747 as well as [the docs](https://argoproj.github.io/argo/windows/)).

In such hybrid clusters it's recommended to schedule workloads to the correct nodes [via the `kubernetes.io/os` node selector](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os).

This label is automatically set on each node so there shouldn't be any compatibility issues when using it as a default node selector. Users with hybrid clusters on the other hand get the benefit of not having to specify the node selector themselves.

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by lippertmarkus** [comment]
@benjaminws @stefansedich could you please look into this?

**Comment by stefansedich** [comment]
:cry: I fail at maintainer, I for some reason have a terrible time with GitHub notifications and seeing them, this LGTM can we get it rebased and I will get it in.

**Comment by lippertmarkus** [comment]
done :)

**Comment by lippertmarkus** [comment]
@stefansedich thanks for taking the time to look at this. Just to make sure: did you see #402 also?

**Comment by stefansedich** [comment]
I did! I have the day off today but it's on my list to check out first
thing in the morning.

**Pull request merged**
