### PR TITLE
feat(argo-workflows): add caSecret in s3 configuration

### PR DESCRIPTION
**Pull request by alexisdondon**
Resolves https://github.com/argoproj/argo-helm/issues/2518

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexisdondon** [comment]
https://github.com/argoproj/argo-helm/issues/2518

**Review by yu-croco — CHANGES_REQUESTED** [review]
Thank you for your PR.

> I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).

Please handle this.

**Comment by alexisdondon** [comment]
> Thank you for your PR.
> 
> > I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
> 
> Please handle this.

Hi, i have added this

**Review by yu-croco — APPROVED** [review]
LGTM

**Pull request merged**
