### PR TITLE
chore(github): Add tico24 to codeowners

### PR DESCRIPTION
**Pull request by tico24**
At the requets of @jmeridth I have popped my name down on the products I'm most familiiar with to offer my services in reviewing/fixing helm things.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Review by mkilchhofer — APPROVED** [review]
Welcome on board 🚀 

Already sent you the invitation to join our GitHub repo

**Comment by mkilchhofer** [comment]
> I assume I can ignore the linting failure?

Yup. Today GH is very unstable.

**Review by yu-croco — APPROVED** [review]
🎉

**Comment by tico24** [comment]
> Yup. Today GH is very unstable.

on that note... I haven't received an invite :)

**Pull request merged**
