### PR TITLE
fix(argo-cd): remove charts/argo-cd/charts/redis-ha/ from git tree

### PR DESCRIPTION
**Pull request by hairmare**
This most likely fixes the issues I have been seeing in #502. As it turns out line `**/charts/*/charts` was introduced to `.gitignore` in #361 even though the now ignored  path `charts/argo-cd/charts/redis-ha` was not removed at the same time.

I'll undraft this and fill in the checklist once I know if it makes the build go green!

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA ~~and the build is green.~~
* [x] the build is green
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by hairmare** [comment]
I think this is failing because CircleCI only uses the `.circleci` folder from the main branch.

When I run it locally using ct v3.3.1 i get the following output:

```
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 argo-cd => (version: "2.11.1", path: "charts/argo-cd")
------------------------------------------------------------------------------------------------------------------------

"argo" already exists with the same configuration, skipping
"dandydeveloper" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "suse" chart repository
...Successfully got an update from the "kubernetes-dashboard" chart repository
...Successfully got an update from the "dandydeveloper" chart repository
...Successfully got an update from the "argo" chart repository
...Successfully got an update from the "caasperli" chart repository
...Successfully got an update from the "sentry" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "adfinis" chart repository
...Unable to get an update from the "kubernetes-charts.storage.googleapis.com" chart repository (https://kubernetes-charts.storage.googleapis.com):
	failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "flux-ui" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "storage.googleapis.com" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading redis-ha from repo https://charts.helm.sh/stable
Deleting outdated charts
Linting chart 'argo-cd => (version: "2.11.1", path: "charts/argo-cd")'
Checking chart 'argo-cd => (version: "2.11.1", path: "charts/argo-cd")' for a version bump...
Old chart version: 2.11.0
New chart version: 2.11.1
Chart version ok.
Validating /home/lucasb/Documents/git.repos/argoproj/argo-helm/charts/argo-cd/Chart.yaml...
Validation success! 👍
Validating maintainers...
==> Linting charts/argo-cd
[ERROR] templates/crds.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
[ERROR] templates/crds.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
[WARNING] /home/lucasb/Documents/git.repos/argoproj/argo-helm/charts/argo-cd: chart directory is missing these dependencies: redis-ha

Error: 1 chart(s) linted, 1 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✖︎ argo-cd => (version: "2.11.1", path: "charts/argo-cd") > Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Error processing charts
Error linting charts: Error processing charts
```

IMO it makes more sense to not fix these issues in this PR. Initially I tried to only focus on removing the erroneous `charts/argo-cd/charts/redis-ha/` path from the git tree but ended up adding a `s@https://kubernetes-charts.storage.googleapis.com@https://charts.helm.sh/stable@` change as well.

Would you prefer if I try to create a PR that contains the contents of #502 as well as #520 in additional to these changes? I think that might build on CircleCI but I would have to create a PR to test that thesis.

**Comment by cabrinha** [comment]
@hairmare please rebase

**Comment by hairmare** [comment]
`scripts/publish.sh` is now failing 
```
+ helm --debug package /root/project/charts/argo-cd
Error: found in Chart.yaml, but missing in charts/ directory: redis-ha
helm.go:81: [debug] found in Chart.yaml, but missing in charts/ directory: redis-ha
helm.sh/helm/v3/pkg/action.CheckDependencies
	/home/circleci/helm.sh/helm/pkg/action/install.go:606
helm.sh/helm/v3/pkg/action.(*Package).Run
	/home/circleci/helm.sh/helm/pkg/action/package.go:78
main.newPackageCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/package.go:103
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

Exited with code exit status 1
```

More info is in https://github.com/argoproj/argo-helm/pull/270#issuecomment-608695684 ff. I'll look a bit further into finding the corresponding helm issues and am marking this as draft once again (it reproduces locally now).

**Comment by hairmare** [comment]
I refactored `publish.sh` so it uses an unpackaged version of the redis-ha chart from the yaml file for the build (instead of using a locally commited version).

As per https://github.com/argoproj/argo-helm/pull/270#issuecomment-611102715 using an alias for `redis-ha` will make more sense in the long run.

I'm hoping this will make the subchart upgradable without needing much changes elsewhere.

**Review by spencergilbert — APPROVED** [review]
LGTM, thanks

**Pull request merged**
