### PR TITLE
feat(operator): Add ArgoCD Operator

### LINKED ISSUE #959: feat(operator): Add ArgoCD Operator Helm Chart
### Is your feature request related to a problem?

This chart bootstraps the ArgoCD Operator on a Kubernetes cluster using the Helm package manager.

We use this with great success with Terraform and was wondering with adjustments if is something ArgoProj would take?

### Related helm chart

other

### Describe the solution you'd like

Please the the associated P.R. 

https://github.com/argoproj/argo-helm/pull/958

### Describe alternatives you've considered

https://github.com/argoproj/argo-helm/pull/958

### Additional context

https://github.com/argoproj/argo-helm/pull/958

### PR DESCRIPTION
**Pull request by sylus**
This is just to get the discussion going on adding a Helm chart for calling the ArgoCD Operator.

This Helm chart bootstraps the ArgoCD Operator on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package manager.

We use this with great success with Terraform and was wondering *with adjustments* if is something ArgoProj would take?

* https://github.com/argoproj-labs/argocd-operator (source)
* https://github.com/StatCan/charts/tree/master/stable/argocd-operator (helm chart) <-- this p.r.
* https://github.com/canada-ca-terraform-modules/terraform-kubernetes-argo-cd (terraform) <-- linked as reference

Create the `argocd-operator-system` namespace and associated RBAC (left to implementor):

```sh
resource "kubernetes_namespace" "argocd_operator_system" {
  metadata {
    name = "argo-cd-system"

    labels = {
      "istio-injection"                 = "enabled"
      "namespace.statcan.gc.ca/purpose" = "system"
    }
  }
}
```

Call our `terraform-kubernetes-argocd-operator` Terraform module.

```sh
module "argocd_operator" {
  source = "git::https://github.com/canada-ca-terraform-modules/terraform-kubernetes-argo-cd.git?ref=v2.0.0"

  chart_version   = "0.1.2"
  helm_repository = "https://statcan.github.io/charts"
  helm_namespace  = kubernetes_namespace.argocd_operator_system.id

  projects = [
    {
      name           = "project-system"
      namespace      = "project-system"
      classification = "unclassified"
      spec = {
        image = {
          repository = "argoproj/argocd"
          tag        = "sha256:0bbcd97134f2d7c28293d4b717317f32aaf8fa816a1ffe764c1ebc390c4646d3"
        },
        kustomizeBuildOptions = "--load-restrictor LoadRestrictionsNone --enable-helm",
        oidcConfig = {
          name         = "project-system"
          issuer       = "https://login.microsoftonline.com/XXXXX-XXXXX-XXXXX/v2.0"
          clientID     = "XXXXX-XXXXX-XXXXX"
          clientSecret = var.argocd_operator_client_secret
          requestedIDTokenClaims = {
            groups = {
              essential = true
            }
          }
          requestedScopes = ["openid", "profile", "email"]
        },
        rbac = {
          defaultPolicy = "role:readonly"
          policy        = <<EOT
            p, role:org-admin, applications, *, */*, allow
            p, role:org-admin, clusters, get, *, allow
            p, role:org-admin, repositories, get, *, allow
            p, role:org-admin, repositories, create, *, allow
            p, role:org-admin, repositories, update, *, allow
            p, role:org-admin, repositories, delete, *, allow
            g, "XXXXX-XXXXX-XXXXX", role:org-admin
          EOT
          scopes        = "[groups]"
        },
        server = {
          autoscale = {
            enabled = true
          }
          host     = "project-system-argocd.example.ca"
          insecure = true
        }
      }
    }
  ]

  values = <<EOF
operator:
  clusterDomain: ""
  nsToWatch: "argo-cd-system"
  nsClusterConfig: ""

  image:
    pullPolicy: IfNotPresent
EOF
}
```

Resolves #959

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Hi @sylus
As there are no other responses from someone in this repo so far, I'd like to ask if you want to help us maintain this in the future. There is an open issue to advertise for maintainers: https://github.com/argoproj/argo-helm/issues/612

Neither me and my employer use the operator of ArgoCD, so I can only evaluate form the helm perspective.

**Comment by sylus** [comment]
Hi @mkilchhofer I would definitely do that as it would be so cool for me to help support Argo in any way I could :)

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
> Hi @mkilchhofer I would definitely do that as it would be so cool for me to help support Argo in any way I could :)

Cool, could you then implement the following:
1. Add yourself to the CODEOWNER
2. Use the helm-docs notation in values.yaml
3. Generate the README.md with a dedicated README.md.gotmpl using helm-docs

**Comment by jmeridth** [comment]
@sylus is it safe to assume this can be closed?

**Comment by sylus** [comment]
Hi @jmeridth sorry I have been away as a key project is taking my attention atm, however I would still be interesting in maintaining but I could reopen / open a new ticket when have more time so feel free to close as don't want to be a pain :)

**Pull request closed without merging**
