### PR TITLE
chore: Add/invite new code-owners

### PR DESCRIPTION
**Pull request by alexec**
@vladlosev @yann-soubeyrand  @davidkarlsen @mr-sour @VaibhavPage

You're all submitting >= 3 PRs that have been accepted into the argo-helm repo. Would you be interested in becoming code-owners and PR approvers?

@benjaminws @stefansedich @paguos @seanson @spencergilbert @jbehling @cabrinha

Thoughts? Are you all able to review the occasional PR? It might be best if people who will never have time to do this are not in the CODEOWNERS file as it might give community members false expectations. You can still remain on the approver's list.

### CODE REVIEW

**Comment by paguos** [comment]
I willing to be more active. But I don't receive the review notifications :/ (And I'm recovering from COVID, will be back at full force in about two weeks 👍🏼)

**Comment by davidkarlsen** [comment]
I don't have too much bandwidth atm, but I guess this is quite low-effort and not too much traffic - so I'm fine with that, even better if we are more ppl so we can share the burden.

**Comment by cabrinha** [comment]
I review PRs and pay attentions to notifications on a weekly basis.

**Review by cabrinha — APPROVED** [review]

**Comment by alexec** [comment]
> I'm recovering from COVID

Get well soon!

**Comment by vladlosev** [comment]
I feel I am now familiar with the `argo` chart and the code to be able to give reviews there,  but I am not feel as confident about `argo-events`.

**Review by vladlosev — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
@vladlosev @davidkarlsen you should have just received an invite. Once accepted, you'll be able to approve and merge PRs.

Now we wait for @yann-soubeyrand @mr-sour so see if they'd like to help

**Comment by yann-soubeyrand** [comment]
> Now we wait for @yann-soubeyrand @mr-sour so see if they'd like to help

Sure, mostly on Argo CD though (at least in a first time).

**Review by seanson — APPROVED** [review]

**Comment by davidkarlsen** [comment]
Sorry, I was a bit quick on this one I believe. But if @mr-sour want's in our out we can adjust accordingly.

**Pull request merged**
