### PR TITLE
fix(argo-cd): Fix Redis race condition due to optional REDIS_PASSWORD

### PR DESCRIPTION
**Pull request by yu-croco**
Resolves https://github.com/argoproj/argo-helm/issues/2836

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by kad-vriese1** [comment]
When will this PR be merged? At this moment ArgoCD does not function after an inital install. A restart of the deployments helps as a workaround but it would be nice if this PR was merged.

**Review by mbevc1 — APPROVED** [review]

**Comment by tico24** [comment]
Is this still a draft @yu-croco? That's why I've been avoiding reviewing.

**Comment by yu-croco** [comment]
I've been waiting for the reply in https://github.com/argoproj/argo-helm/issues/2836#issuecomment-2238842115, but we cannot get reply. So let us go proceed.

**Comment by mbevc1** [comment]
If we cannot get a reply, I agree let's go ahead and merge this. Feels like the risk is fairly low.

**Comment by kad-vriese1** [comment]
Thank you!

**Review by mkilchhofer — COMMENTED** [review]
LGTM 👍

**Comment by purajit** [comment]
Btw, this didn't fix #2836 from what I can tell.

**Pull request merged**
