### PR TITLE
fix(argo-cd): Rename tls secret to include the -secret suffix

### PR DESCRIPTION
**Pull request by karlparry**
PR supersedes <https://github.com/argoproj/argo-helm/pull/1675>

Signed-off-by: Karl Parry <karl.parry@imbursepayments.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Why do we need this? Please describe your intent. Its just a filename.

**Review by pdrastil — APPROVED** [review]
LGTM - Thanks for the fix

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Can we add 
```yaml
        {{- if .Values.repoServer.certificateSecret.enabled }}
        checksum/repo-server-tls: {{ include (print $.Template.BasePath "/argocd-configs/argocd-repo-server-tls-secret.yaml") . | sha256sum }}
        {{- end }}
```
To the repo-server as well?

**Comment by karlparry** [comment]
Of course. I will do it now

**Comment by karlparry** [comment]
Its to fix a bug where if you enable TLS for Dex the current Helm chart fails. This is to fix that and also standardise the secret yaml namining.

**Comment by karlparry** [comment]
PR updated with Repo Server checksum, also updated the chart.yaml changelog with more details

**Review by mkilchhofer — APPROVED** [review]
LGTM. Thank you 🙏

**Comment by karlparry** [comment]
Thanks, once this is merged I plan to roll this out to production so if there are any more issues enabling the TLS I will raise some further PRs

**Pull request merged**
