### PR TITLE
fix(argo-cd): Allow to disable containerSecurityContext

### PR DESCRIPTION
**Pull request by hsmade**
Use `with` so (parts of) the securityContext can be `null`ed out. Fixes https://github.com/argoproj/argo-helm/issues/2071

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by hsmade** [comment]
wait, this won't work. Because it will try to serialise the `enabled` as well

**Comment by hsmade** [comment]
> 



> Just use `with` instead of `if`. Then for the `toYaml` parameter, you can simply reference `.` and you're good to go :)

Not sure how this will work (not that experienced with Helm per se). But `with` would just change the scope right, it won't allow us to not use the dict values if `enabled` is set to `false`? Because that's what I'm trying to do.

I'm trying to work around a long standing bug in Helm, where it doesn't allow you to override a map.
Right now, it's not possible to disable the security context at all (not even by setting it to `null`).

**Review by mkilchhofer — APPROVED** [review]

**Review by jmeridth — APPROVED** [review]

**Comment by hsmade** [comment]
(note that while this makes the code more consistent (with the global.securityContext), it doesn't solve the issue linked. When using this chart as a subchart, it still fails to override, due to the (longstanding) bug in Helm

**Comment by SomniVertix** [comment]
@hsmade  - Is there any workaround or link to the helm bug?

**Comment by mkilchhofer** [comment]
Helm refs:
- https://github.com/helm/helm/issues/9136
- https://github.com/helm/helm/issues/9027

**Pull request merged**
