### PR TITLE
chore(argo-rollouts): Bump rollouts to 1.6.1

### PR DESCRIPTION
**Pull request by DrFaust92**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @DrFaust92 , thank you for your PR.
Since we want to support all of the new versions as Chart version, can you please separate PR ?
1. `v1.6.0` -> `v1.6.1`
2. `v1.6.1` -> `v1.6.2`

**Comment by DrFaust92** [comment]
Sure, will do

**Comment by DrFaust92** [comment]
[yu-croco](https://github.com/yu-croco) Done

**Review by yu-croco — APPROVED** [review]
LGTM 👍

**Review by tico24 — APPROVED** [review]

**Pull request merged**
