### PR TITLE
fix(argo-cd): Fix applicationSet HA examples in README.md

### PR DESCRIPTION
**Pull request by joonvena**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Review by yu-croco — CHANGES_REQUESTED** [review]
Hi @joonvena , thank you for your PR.
Can you please handle below (items that are written in PR description)?

> I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)

Please bump patch version [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml#L6).

> I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).

Please remove old block and add new block [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml#L28-L30)

**Comment by joonvena** [comment]
Hi, added changes.

**Review by yu-croco — APPROVED** [review]
Thank you for your contribution. LGTM.

**Review by jmeridth — APPROVED** [review]

**Comment by mbevc1** [comment]
Thanks, could you please fix conflicts?

**Comment by joonvena** [comment]
Done probably the Chart version should be bumped again as the latest change in main already has the 5.43.6.

**Comment by yu-croco** [comment]
Please bump the version to `5.43.7` since the other PR took `5.43.6` 🙏

**Comment by joonvena** [comment]
Bumped to `5.43.7`

**Pull request merged**
