### PR TITLE
feat: Added possibility to override BASE_HREF env variable…

### PR DESCRIPTION
**Pull request by geoL86**
Added possibility to override BASE_HREF env variables through values

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by geoL86** [comment]
@benjaminws - done, thanks ...

**Comment by terev** [comment]
@benjaminws i submitted a pr for this as well. could this be merged now?

**Comment by terev** [comment]
@geoL86 could you add something like this comment i included here: https://github.com/argoproj/argo-helm/pull/243/files#diff-622b201eb137f7621968873de4b70048R110-R112 it points out to the user that the path is supposed to be rewritten before the request is passed to the backend

**Comment by terev** [comment]
@benjaminws checking in again, sorry to bother. could we have this merged now?

**Comment by terev** [comment]
@alexec could we get a review on this? it's blocking me from deploying the ui behind a reverse proxy

**Comment by terev** [comment]
@alexec @alexmt @jessesuen hey any chance we can get a review on this?

**Comment by benjaminws** [comment]
@terev Ah, can you fix up the conflicts real quick? We can merge it immediately after.

**Comment by terev** [comment]
@benjaminws np i totally understand :) . @geoL86 could you have a look at fixing the conflicts?

**Comment by geoL86** [comment]
@terev @benjaminws  I've done it, but I don't even hope so ...

**Comment by alexec** [comment]
Merged. I think these charts automatically release.

**Comment by terev** [comment]
@geoL86 so unfortunately when merge conflicts were being resolved the part that actually templates the value was lost https://github.com/argoproj/argo-helm/pull/216/commits/4eb7f3e5873ccf9cf5824d1aa4cbc9f8af2aa7cb#diff-0bfa79b4fdeddb715af81854063030a3R62

**Comment by terev** [comment]
@geoL86 @alexec i've submitted a pr with a fix for this: https://github.com/argoproj/argo-helm/pull/261

**Comment by kristofarkas** [comment]
FYI fixed the server deployment to actually use the value as part of https://github.com/argoproj/argo-helm/pull/263

**Pull request merged**
