### PR TITLE
feat(argo-cd): Global support for toleration, affinity and nodeSelector

### PR DESCRIPTION
**Pull request by rupinSec**
fixes: #1775 

Added toleration , affinity and nodeSelector support for the global support. 

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Hi @rupinSec, thanks for your contribution.

I think we could add that feature, although your implementation is a bit noisy.

We should use the with `mergeOverwrite` and `deepCopy` features of helm.
You find examples on howto use this on `podAnnotations`:

`{{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.controller.podAnnotations) }}`

Can you have a look into this and update your PR?

**Comment by rupinSec** [comment]
Hi @mkilchhofer,
I have made changes as mentioned by you. 

Please review again.

Thanks

**Comment by pdrastil** [comment]
@mkilchhofer Global affinity will not work well. Each component have different selector labels typically used for pod anti-affinity. I would prefer to rather implement soft / hard options properly with possibility to override on component level.

**Comment by mkilchhofer** [comment]
> @mkilchhofer Global affinity will not work well. Each component have different selector labels typically used for pod anti-affinity. I would prefer to rather implement soft / hard options properly with possibility to override on component level.

Oh sure, you are right. 👍 
But I am not sure how to proceed in this PR, then. For a Hard/soft constraint within one component IMO topologySpreadConstraint fits better.

**Comment by pdrastil** [comment]
@mkilchhofer This is what I originally had in store https://github.com/argoproj/argo-helm/pull/1794 . I believe we can extend this with node selectors, tolerations and priority class name.

**Comment by rupinSec** [comment]
@mkilchhofer @pdrastil Can you guys specify what changes I need to do in this PR.

**Comment by rupinSec** [comment]
@mkilchhofer Can you please reply for my above question. I can see a PR with similar feature but it also in pending state (#1794).

**Comment by pdrastil** [comment]
Closing as implemented via https://github.com/argoproj/argo-helm/pull/1846

**Pull request closed without merging**
