### PR TITLE
feat(argo-cd): Add dnsConfig and dnsPolicy for pods

### LINKED ISSUE #1771: Add a way to specify DNS configuration for the pods
### Is your feature request related to a problem?

I need to add extra configuration to the pod in order to specify a DNS and a DNS policy, this is not currently possible in the chart.

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like to be able to add general configuration to the pod, using an `extraPodConfig` key.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by loristo**
Resolves #1771

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — CHANGES_REQUESTED** [review]
Hi @loristo 

Thanks for your contribution on our project.
I don't like such a generic variant of implementing customization of a Pod as it would be hard to guess what customization customers of this project use. Therefore there might be an easily a conflict between a future update of our chart (eg with a minor veriosn bump) and your customization.

Could you elaborate your use case?

**Comment by loristo** [comment]
Hello @mkilchhofer

Thank you for your answer.
I totally understand your answer and agree that it could be an issue with future releases.

My use case was adding a `dnsPolicy` and dnsConfig` key to the deployed pods to be able to use a private DNS. I added the `extraPodConfig` because these options do not impact the overall behavior of ArgoCD, so I thought a generic solution would offer more configuration possibilities. If you prefer, I can change the PR to feature a `dnsPolicy` and `dnsConfig` options in order to be more explicit.

**Comment by mkilchhofer** [comment]
> Hello @mkilchhofer
> 
> Thank you for your answer. I totally understand your answer and agree that it could be an issue with future releases.
> 
> My use case was adding a `dnsPolicy` and `dnsConfig` key to the deployed pods to be able to use a private DNS. I added the `extraPodConfig` because these options do not impact the overall behavior of ArgoCD, so I thought a generic solution would offer more configuration possibilities. If you prefer, I can change the PR to feature a `dnsPolicy` and `dnsConfig` options in order to be more explicit.

Yes, I would prefer to add these two feature separately 👍

**Comment by loristo** [comment]
I have modified the PR accordingly !

**Review by mkilchhofer — APPROVED** [review]

**Review by yu-croco — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
