### PR TITLE
feat(argo): bump apiVersion and support helm3

### PR DESCRIPTION
**Pull request by clementlecorre**
Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

---

Hello everyone !

https://helm.sh/docs/faq/#chartyaml-apiversion-bump

I propose a change of `apiVersion` in version 2 to have a stability on helm3. 

Thanks 👍

### CODE REVIEW

**Comment by stefansedich** [comment]
@clementlecorre just got to checking this one out sorry, looks like it might be time to do this, Helm2 is now gone gone and makes sense to remove support going forward.

I would be more comftorable if we at least bumped to a 0.14.x release, if you want to do that and I get no objections from @benjaminws @seanson or @spencergilbert we will get this merged.

**Comment by clementlecorre** [comment]
@stefansedich Following your advice I have changed the version to a 0.14.x release of the helm chart.

**Comment by seanson** [comment]
Given this only affects the Argo chart and we do not currently use it I have no issue against it.
If it affected argo-cd it would be a blocker for us as we're still stuck on Helm2 until the end of January due to some legacy implementations.

**Review by stefansedich — APPROVED** [review]
LGTM

**Comment by stefansedich** [comment]
Thanks @seanson I went ahead and merged this in without any other objections given, thanks again @clementlecorre

**Pull request merged**
