### PR TITLE
feat(argo-workflows): Bump appVersion to 3.1.5

### PR DESCRIPTION
**Pull request by matt-carr**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by asafhm** [comment]
Seems like this is ready for review, can this be revisited? :)

**Review by oliverbaehler — DISMISSED** [review]
Bump Version according to Contribution Guidelines.

No relevant Changes in crds noticed.
```
oliver@buttahtoaster:~/tmp$ diff argo-helm/charts/argo-workflows/crds/argoproj.io_clusterworkflowtemplates.yaml argo-workflows/manifests/base/crds/minimal/argoproj.io_clusterworkflowtemplates.yaml
28a29
>             x-kubernetes-map-type: atomic              
oliver@buttahtoaster:~/tmp$ diff argo-helm/charts/argo-workflows/crds/argoproj.io_workfloweventbindings.yaml argo-workflows/manifests/base/crds/minimal/argoproj.io_workfloweventbindings.yaml
27a28
>             x-kubernetes-map-type: atomic
oliver@buttahtoaster:~/tmp$ diff argo-helm/charts/argo-workflows/crds/argoproj.io_workflowtemplates.yaml argo-workflows/manifests/base/crds/minimal/argoproj.io_workflowtemplates.yaml
27a28
>             x-kubernetes-map-type: atomic
oliver@buttahtoaster:~/tmp$ diff argo-helm/charts/argo-workflows/crds/argoproj.io_cronworkflows.yaml argo-workflows/manifests/base/crds/minimal/argoproj.io_cronworkflows.yaml
28a29
>             x-kubernetes-map-type: atomic
31a33
>             x-kubernetes-map-type: atomic
oliver@buttahtoaster:~/tmp$ diff argo-helm/charts/argo-workflows/crds/argoproj.io_workflows.yaml argo-workflows/manifests/base/crds/minimal/argoproj.io_workflows.yaml
38d37
<             x-kubernetes-preserve-unknown-fields: true
39a39
>             x-kubernetes-preserve-unknown-fields: true
42d41
<             x-kubernetes-preserve-unknown-fields: true
43a43
>             x-kubernetes-preserve-unknown-fields: true
```

**Comment by matt-carr** [comment]
alright well this is officially profoundly embarrassing and DCO is now my Enemy

**Comment by mbevc1** [comment]
:slightly_smiling_face: 

Seems this one is missing sign-off:
```
Commit sha: f9f5c62, Author: Matt Carr, Committer: GitHub; The sign-off is missing.
```

**Comment by matt-carr** [comment]
True, but then I own the intermediate commits too and DCO wants me to sign them too?

**Review by davidkarlsen — APPROVED** [review]

**Review by mbevc1 — APPROVED** [review]

**Comment by matt-carr** [comment]
okay the power of not looking at this for 16h apparently revealed the solution to me, which was to stop trying to be fancy

**Comment by mbevc1** [comment]
Can you also please update the changelog?

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
