### PR TITLE
fix(argo-workflows): Quick fix for failing deployment when using image digests

### PR DESCRIPTION
**Pull request by clarkjohnd**
Rudimentary fix for Argo Workflows Helm chart when passing either image digests (64 characters) or tags longer than 63 characters by truncating the tag/digest to 63 characters instead. The tag is used in the ```app.kubernetes.io/version``` label in deployments and services in the Argo Workflows charts, and without this fix, the deployments fail due to max character length in labels of 64 characters. Two new tag variables in ```_helpers.tpl``` created and used in controller and server deployment and service.

This could probably do with a PR for proper digest support like [PR 643](https://github.com/argoproj/argo-helm/pull/643) at some point (which I'm happy to do when I get a bit more time) instead of just using the tag parameter, but for now digests are supported by doing the following (using the controller as an example):

```yaml
controller:
  image:
    repository: argoproj/workflow-controller@sha256
    tag: 614275080106101e49c8227a98d12951a73a4c3a9456dc684cff8775a543a35c
```

No changes otherwise and no impact on existing deployments, app version still added to label if no specific tag given. Minor release update to 0.14.0.

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by clarkjohnd** [comment]
Wondering if there is any movement on this? Hoping to implement it into a module I'm working on with this feature soon. Thanks!

**Comment by clarkjohnd** [comment]
Bump again, could really do with this feature. Thanks

**Review by mkilchhofer — APPROVED** [review]
Reworked your PR as its really a quick fix and we can omit the template function for this. Let's hope someone has time to do a proper proposal like your mentioned PR I created some time ago for the Argo CD chart.

**Comment by clarkjohnd** [comment]
Thanks @mkilchhofer, I'll look to do the proper proposal in the coming weeks.

**Pull request merged**
