### PR TITLE
fix(argo-cd): Fully disable Dex when setting `dex.enabled: false`

### PR DESCRIPTION
**Pull request by cten**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by pdrastil** [comment]
These and all other configuration values are very clearly marked as `optional: true` and thus not mandatory. If the value is not provided (which isn't if dex .enabled is false) it's not mounted / used by running a container. IMHO this PR just brings unnecessary conditional behaviour that do not have any effect and it will be harder to do syncs with upstream that adds new values. Thoughts @mkilchhofer @jmeridth

**Comment by cten** [comment]
I understand for the ENVs, I can remove that logic, but for the volumeMounts there is no `optional` option I believe.

**Comment by cten** [comment]
Sorry, I didn't know about the optional setting on volumes/volumeMounts. I will delete this PR and associated Issue.
Thanks

**Comment by pdrastil** [comment]
Hi, no problem. It's relatively new and was introduced with upstream in 2.5.x release for K8s 1.22. This feature simplifies templating on multiple places as it's no longer needed to use if / else for older versions of K8s.

**Pull request closed without merging**
