### PR TITLE
fix(argo-workflows): add clusterrole to avoid workflow-controller errors

### PR DESCRIPTION
**Pull request by menzbua**
This Pull-Request should fix https://github.com/argoproj/argo-helm/issues/2824

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by tico24** [comment]
I don't see this in the upstream clusterrole that the workflow-controller uses. https://github.com/argoproj/argo-workflows/releases/download/v3.5.8/install.yaml

(cluster role starts on line 1016)

In fact those permissions don't appear anywhere in the upstream yaml. This should be fixed upstream before here.

**Comment by menzbua** [comment]
Okay, I will open an issue in the upstream project, and check if we can add the rule there, too.

**Comment by MikeJansen** [comment]
Thank you so much for this!  My simple 2 step HTTP demo workflow went from taking 30 minutes to complete to 50 seconds, and reporting status properly now.  

I just added an argo-fix manifest with a new cluster role and an additional binding  for the controller account until it's fixed upstream in argo-workflows.

**Comment by MikeJansen** [comment]
> Okay, I will open an issue in the upstream project, and check if we can add the rule there, too.

With the latest helm chart this issue still exists.  Did an issue get added upstream?

**Pull request closed without merging**
