### PR TITLE
feat(argo-ci): deprecate argo-ci helm chart

### PR DESCRIPTION
**Pull request by oliverbaehler**
Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>

Since this chart is no longer used we officially should deprecate it. Therefore we can also exclude it for the new lint workflow. Last change has been 8 months ago. 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Review by mkilchhofer — COMMENTED** [review]
Deprecation of this chart makes sense as the [project README](https://github.com/argoproj/argo-ci/blob/master/README.md) says:
> **THIS PROJECT IS NO LONGER MAINTAINED. PLEASE TAKE A LOOK AT ARGO EVENTS INSTEAD (https://github.com/argoproj/argo-events)**

**Review by mkilchhofer — APPROVED** [review]

**Comment by oliverbaehler** [comment]
cc @alexec Since noone is owner you might want to take a quick look at this

**Comment by alexec** [comment]
Is anyone using this chart? I think we could just delete it.

**Comment by mkilchhofer** [comment]
Best practice would be to release a deprecated chart first, then drop the directory from VCS :)

**Comment by alexec** [comment]
merged

**Pull request merged**
