### PR TITLE
feat(argo-rollouts): Add rollouts dashboard ingress support

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
This resolves https://github.com/argoproj/argo-helm/issues/868.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by sergeyshaykhullin** [comment]
values.yaml

```yaml
service:
  annotations: {}
  labels: {}
  portName: dashboard
  port: 3100
  targetPort: 3100
ingress:
  enabled: true
  annotations:
    my-annotation: shows
  labels:
    my-label: shows
  ingressClassName: ""
  hosts:
    - argorollouts.example.com
  paths:
    - /
  pathType: Prefix
  extraPaths:
    - path: /*
      backend:
        serviceName: ssl-redirect
        servicePort: use-annotation
  tls:
    - secretName: argorollouts-example-tls
      hosts:
        - argorollouts.example.com
  https: true
```

templated.yaml

```yaml
# Source: argo-rollouts/templates/dashboard/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    my-annotation: "shows"
  name: test-release-argo-rollouts
  labels:
    helm.sh/chart: argo-rollouts-2.1.0
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/instance: test-release
    app.kubernetes.io/version: "v1.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-rollouts
    my-label: shows
spec:
  rules:
    - host: argorollouts.example.com
      http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
            path: /*
          - path: /
            backend:
              serviceName: test-release-argo-rollouts
              servicePort: 3100
  tls:
    - hosts:
      - argorollouts.example.com
      secretName: argorollouts-example-tls
```

**Comment by sergeyshaykhullin** [comment]
@mkilchhofer Can you please provide some feedback? Does argo team have some plans to add ingress support for rollouts ui?

**Comment by mkilchhofer** [comment]
Hmmm what are you doing with your commits? Something is wrong how you update your PR - since there are 40 commits now from random other contribution, github added all reviewers from all different charts. Can you do a clean rebase?

**Comment by mkilchhofer** [comment]
Also I am unsure if we should provide an Ingress if the upstream project doesn't. I do not use rollouts and therefore I cannot gauge if this is a good idea or not. I think exposing the dashboard via ingress exposes some unauthenticated possibilities to to the cluster?

I'd wait until https://github.com/argoproj/argo-helm/issues/868 is implemented or at least we have feedback from the maintainers.

**Comment by sergeyshaykhullin** [comment]
But... https://github.com/argoproj/argo-helm/issues/868 is my issue and this is an implementation

I will do my best to fix commit problem

**Comment by sergeyshaykhullin** [comment]
You can always use authentication proxy in front of rollouts ui with google/github authentication

E.g. https://github.com/oauth2-proxy/oauth2-proxy

**Comment by sergeyshaykhullin** [comment]
@mkilchhofer Done

**Comment by mkilchhofer** [comment]
> You can always use authentication proxy in front of rollouts ui with google/github authentication
> 
> E.g. https://github.com/oauth2-proxy/oauth2-proxy

Yeah, that would be the minimal needed protection we need, but then we do not need an ingress in this project here.

Anyways, as already mentioned in https://github.com/argoproj/argo-helm/issues/868#issuecomment-945076787 we need a commitment of the upstream project. Please file an issue/PR in the upstream project over there: https://github.com/argoproj/argo-rollouts as we don't want to support things which are unsupported from the upstream team.

**Review by mkilchhofer — APPROVED** [review]
Hi @sergeyshaykhullin 
I thought about your PR again and adapted the warning. For me it's okay now and I approve this PR. Sorry for the long waiting period.

Thanks for your contribution 🙏

**Pull request merged**
