### PR TITLE
fix(argo-cd): Remove AWS volume from server

### PR DESCRIPTION
**Pull request by pdrastil**
Closes: https://github.com/argoproj/argo-helm/issues/1589

---

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by mbevc1** [comment]
Is https://github.com/argoproj/argo-helm/pull/1006 not relevant anymore?

**Comment by pdrastil** [comment]
AWS CLI is not a part of Argo CD image as it's cloud agnostic. After discussion with @mkilchhofer we are more incline to remove it and if people need this they should add it via volumes / volumeMounts.

**Comment by mbevc1** [comment]
Sure, makes sense. I was just wondering how come we've had it in the first place and making sure we're not breaking anything :) Cheers

**Review by mbevc1 — APPROVED** [review]

**Comment by pdrastil** [comment]
@mbevc1 It's user extension that was added for AWS cloud. It's not part of upstream manifests.

**Pull request merged**
