### PR TITLE
fix(argo-cd): Update applicationset clusterrole verbs by analogy with ns-scoped role

### PR DESCRIPTION
**Pull request by hodorov**
Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

### CODE REVIEW

**Comment by yu-croco** [comment]
Hi @hodorov thank you for opening PR.
argo-helm follows upstream's manifest and [upstream's applicationset-clusterrole](https://github.com/argoproj/argo-cd/blob/v2.12.0/manifests/cluster-rbac/applicationset-controller/argocd-applicationset-controller-clusterrole.yaml#L32-L37) doesn't have `list` and `watch ` .
Could you please open an issue in upstream about it?

**Comment by hodorov** [comment]
@yu-croco Just work on it. PR https://github.com/argoproj/argo-cd/pull/19430 with linked issue https://github.com/argoproj/argo-cd/issues/19059

**Comment by hodorov** [comment]
@yu-croco Hello again. Manifest in upstream ```master``` branch updated, also commit cherry-picked into ```release-2.12``` branch. Should we wait until argo-cd release 2.12.1 version or may update chart right now?

**Comment by tico24** [comment]
>Should we wait until argo-cd release 2.12.1 version or may update chart right now?

The chart aligns with the released versions only, so you should wait.

**Comment by pdrastil** [comment]
Resolved via https://github.com/argoproj/argo-helm/pull/2885

**Pull request closed without merging**
