### PR TITLE
chore(argo-cd): Helm dependency update for redis-ha v4.23.0 

### PR DESCRIPTION
**Pull request by ab-ty**
Helm dependency update for redis-ha v4.23.0  and redis images to 7.0.9-alpine

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Comment by mbevc1** [comment]
Thanks for your contribution. Could you please sign off your commits? 
https://github.com/argoproj/argo-helm/pull/1879/checks?check_run_id=11721677994

**Comment by pdrastil** [comment]
Also please regenerate docs via `scripts/helm-docs.sh` to get build passing.

**Comment by ab-ty** [comment]
Regenerated the docs, the commits seem to be signed for me in the CLI 
```
commit c0fd88f55dcdcbb0deba6ccdc74bc42bd643488f (HEAD -> update-redis-ha-chart, origin/update-redis-ha-chart)
  Author: AB-ty <109608598+ab-ty@users.noreply.github.com>
  Date:   Tue Mar 7 00:06:29 2023 +0100
  
      Regenerate docs
  
  commit f680e938ebed089bb1ebf393dcbf00aba9c5b624 (main)
  Author: AB-ty <109608598+ab-ty@users.noreply.github.com>
  Date:   Thu Mar 2 17:26:18 2023 +0100
  
      Helm dependency update for redis-ha V4.23.0 and redis images to 7.0.9-alpine
  
  commit 9663ca2fbdc060166fba7ce19898431c3e5e2b85 (tag: argo-rollouts-2.22.3, upstream/main, origin/main, origin/HEAD)
  Author: Aikawa <yu.croco@gmail.com>
  Date:   Fri Mar 3 00:02:33 2023 +0900
  
      chore(argo-rollouts): Upgrade Argo Rollouts to v.1.4.1 (#1877)
      
      * chore(argo-rollouts): Upgrade Argo Rollouts to v.1.4.1
      Signed-off-by: yu-croco <yu.croco@gmail.com>
      
      * chore(argo-rollouts): Add update information
      Signed-off-by: yu-croco <yu.croco@gmail.com>
      
      ---------
      
      Co-authored-by: Jason Meridth <jmeridth@gmail.com>
  

```

**Comment by mbevc1** [comment]
Are all commits signed off? Also could you please bump Cahrt version as well?
```  ✖︎ argo-cd => (version: "5.24.1", path: "charts/argo-cd") > chart version not ok. Needs a version bump! ```

**Comment by mkilchhofer** [comment]
@ab-ty please rebase (maybe squash) your commits and make sure that you sign-off your commits by adding the `-s` option to `git commit`. It is required to pass DCO checks.

**Pull request closed without merging**
