### PR TITLE
feat(argocd-image-updater): Add hooks for creating secrets

### PR DESCRIPTION
**Pull request by ulfox**
Bump chart version

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by ulfox** [comment]
I was thinking that this could be easier to maintain if it the scripting was moved as part of a container.

- apt install would not be needed
- we can use more advanced scripting (compared to when we write scripts in the job's arguments)

WDYT?

**Comment by mkilchhofer** [comment]
Hmm I don't use this image updater. But reading the upstream documentation you're implementing an edge case, right? This is only needed if ArgoCD runs on a different cluster than the image updater, right?

**Comment by ulfox** [comment]
It can work with the same cluster also. Essentially it auto-creates the secret `argocd-image-updater-secret` that is required by image updater to communicate with ArgoCD. If I am not mistaken that secret part requires manual steps.

With the chart hooks we can auto create this secret. The only requirement is that argocd has an account with apiKey capability.

Is this functionality already implemented in the image updater and I completely missed that out?

**Comment by mkilchhofer** [comment]
As far as I understand is that the upstream team from argoproj-labs implented a method to communicate to ArgoCD via native K8s (through RBAC/CRDs).
Someone tried to implemented this in this PR here: https://github.com/argoproj/argo-helm/pull/918

Xref for upstream: https://github.com/argoproj-labs/argocd-image-updater/pull/144

**Comment by ulfox** [comment]
Hm, makes sense. I was not aware of that. Will close this PR then!

**Pull request closed without merging**
