### PR TITLE
chore(argo-cd): Fix typo of policy.csv comment in values.yaml

### PR DESCRIPTION
**Pull request by KENNYSOFT**
Question:

Since it's extra-small PR and only fixes the comment, would I still have to update the chart version or changelog?

---
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
> Since it's extra-small PR and only fixes the comment, would I still have to update the chart version or changelog?

Unfortunately yes, otherwise our pipeline (required) is not green.

**Comment by KENNYSOFT** [comment]
> > Since it's extra-small PR and only fixes the comment, would I still have to update the chart version or changelog?
> 
> Unfortunately yes, otherwise our pipeline (required) is not green.

I see. I've asked since I cannot know before any contributor approves the workflow run; will do it.

**Comment by mbevc1** [comment]
Thanks for your contribution @KENNYSOFT :+1: . Could you also please update your branch with `master`?

**Comment by KENNYSOFT** [comment]
> Thanks for your contribution @KENNYSOFT 👍 . Could you also please update your branch with `master`?

Sure, thanks for the guide. I saw other PRs are squashed, so I think updating with merge or rebase is both available options. I'll take the former.

**Review by mkilchhofer — APPROVED** [review]

**Pull request merged**
